### ISSUE TITLE
App asks to be connected to the internet when searching a book

### ISSUE THREAD

**Issue by EdoSecco** [tfonteyn/NeverTooManyBooks#1]
When I search a book (both via ISBN and title) the app does not recognise that the phone is connected to internet and does not do the search.

**Comment by tfonteyn** [comment]
make sure you're on 3.4.1 (3.4.0 had a bug) and check in the settings, under the "Search" header:
 "Allow mobile data usage" -> flip it on if needed.

**Comment by EdoSecco** [comment]
Yes it's 3.4.1 and I set up the mobile data, but it still shows that message.

**Comment by tfonteyn** [comment]
it's rather weird - the logic in that bit of code has not changed for a long time (as long as the setting is on) but heck, lets see what's going on.
 Can you please get into "Settings", scroll down to the bottom and choose "maintenance"... then "bug report". Just check the "log files" + "settings" and click "ok"... it will ask to email.
My apologies, but I still have not setup a dedicated email. So just grab the attachments + the info-text and post them here.
(hum, thats a point... I will enhance the app to make that easier... better then email really)

**Comment by EdoSecco** [comment]
Here we go!

[NTMBBugReport-2022-12-08T191531.733.zip](https://github.com/tfonteyn/NeverTooManyBooks/files/10188407/NTMBBugReport-2022-12-08T191531.733.zip)

App: com.hardbacknutter.nevertoomanybooks
Version: 3.4.1 (23, 2022-11-27T15:22:03.8878958)
SDK: 8.0.0 (26 release-keys)
Model: SM-A520F
Manufacturer: samsung
Device: a5y17lte
Product: a5y17ltexx
Brand: samsung
Build: R16NW
Signed-By: df:97:1c:e7:d5:8d:3c:df:37:7c:32:e0:e2:f5:3d:65:99:bd:7f:13:0a:50:c0:52:9c:45:58:3d:dc:12:a0:08

logScreenParams|

configuration:
  screenWidthDp=360
  screenHeightDp=616
  orientation=PORTRAIT
  densityDpi=480
metrics:
  widthPixels=1080
  heightPixels=1920
  density=3.0

**Comment by tfonteyn** [comment]
well, this is embarrassing - SM-A520F ... you have the exact same model as my own phone - so it should have worked perfectly.
Also, there were no error logs in the zip which makes it even stranger.

ok - what was the *exact* error message?
And what was the ISBN you tried to lookup ?

Can you make sure to try the lookup (by ISBN); note the exact error message; and then use the bug-report option again.
I just want to make sure to capture any logs.

**Comment by tfonteyn** [comment]
btw, unless you're in the US, you will want to update the amazon url to your preferred/local one:

"Settings", under the "Search" category, select "More..." then "Amazon" and update the URL.

**Comment by EdoSecco** [comment]
I'm so sorry, the problem was caused by an app that filters the internet connectivity of the phone (personalDNSfilter), now it works perfectly.

**Comment by tfonteyn** [comment]
no worry - glad it works now. Please feel free to log any other issues or improvements request.
