### ISSUE TITLE
Searching for the book failed.

### ISSUE THREAD

**Issue by francois072** [tfonteyn/NeverTooManyBooks#10]
No matter which book's title I search for in order for it to be added to my library I always get a message "Searching for the book failed"

**Comment by tfonteyn** [comment]
I'll need some details to be able to check this:
- I presume you are searching by "search internet", which is by Author and Title?
  Searching by ISBN (either scanning, or "Enter ISBN") is much more accurate.
- Can you give me an example of a book you fail to find?
- Which search-sites have you enabled? Check this in "Setting, Websites" on the 1st tab "books"
- Likewise, make sure you set the Amazon site to your preferred/local one via "Settings, under heading "search", choose "More...", scroll down to the list of web sites and click/edit Amazon.
- Please generate a debug report via: Settings, scroll down to the bottom, Maintenance, then "debug report". This will generate a zip file which you can attach here. Make sure to enable the report to include "settings" and "log files"

**Comment by francois072** [comment]
Expamle book: How to analyze people. Daniel Spade.
ISBN: 9781072375319

No local Amazon website is available.

[ntmb-debug-2023-05-16.zip](https://github.com/tfonteyn/NeverTooManyBooks/files/11486586/ntmb-debug-2023-05-16.zip)

**Comment by tfonteyn** [comment]
Thanks for that - I've reproduced and fixed it already. I'll create and upload a new release later today.

    No local Amazon website is available.

that's ok, by default the US one is searched.

However, I strongly advice to **always** use the ISBN if you have it. From the "+" button you can choose "scan ..." or manually enter it with "Enter ISBN". Search results will be faster and more reliable.
Also: not all sites are supported for plain author/title searches (see Setting/Websites) where each site lists how it can be searched.

Searching on Author/Title is really just needed for old books which were issues without an ISBN.

The example you gave looked up by ISBN will give full details and the get cover images. Searching the same book (with the new fix/release) will only return limited info and no cover image.

I'll put a note here when the new release is uploaded.

edit: upload will be later today; I have some things to attend to first. Please just use ISBN.

**Comment by tfonteyn** [comment]
and here we go: [v4.3.4](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.3.4)

But as mentioned, using the ISBN is just easier
