### ISSUE TITLE
Fetch covers from the internet in portrait is not usable

### ISSUE THREAD

**Issue by maverick74** [tfonteyn/NeverTooManyBooks#12]
Fetching covers from the internet in portrait mode is not usable as the popup is "too slim"
(landscape mode is OK)

![Screenshot_2023-05-16-20-33-59-838_com hardbacknutter nevertoomanybooks](https://github.com/tfonteyn/NeverTooManyBooks/assets/14912461/bd38f7fe-29ca-4aff-9bfe-35a732fec80b)

**Comment by tfonteyn** [comment]
I should have seen this issue coming as I had the same issue for some other dialogs. I've just fixed this one as well now.
It's to late tonight, but you can expect a new release tomorrow.

A bit of an explanation: I tried to implement dialogs in such a way that they are automatically full-screen or a real-dialog depending on screen size. I've started to admit defeat... there are just to many different types of screen out there.
I'm more or less settling now on full-screen dialogs for all devices which have a diagonal of less than 7", and real-dialog style for 7" and larger screens.

**Comment by maverick74** [comment]
> I'm more or less settling now on full-screen dialogs for all devices which have a diagonal of less than 7", and real-dialog style for 7" and larger screens.

Seems a good approach!

**Comment by tfonteyn** [comment]
and another bug fixed: [v4.3.5](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.3.5)
