### ISSUE TITLE
Progression (read pages)

### ISSUE THREAD

**Issue by PawelGu** [tfonteyn/NeverTooManyBooks#16]
Would be awesome to have not only an option to tick 'read' but also which page is the current (I read the same books on many different devices).

**Comment by tfonteyn** [comment]
Adding this field and putting it on the "book edit" screen would be no problem. I can do that.

But I'm struggling a bit on how to integrate it with the single-tick on the "book details" (or on the booklist via the row/context  menu). The point of the simple checkbox/menu-option was to have a minimal-effort approach to toggling the status.

maybe...
- "book detail": allow a "long-click" on the 'read' option brings up a dialog? But what to do on the booklist row/context menu? And a "long-click" (as I learned myself) is not that intuitive to discover without reading the documentation.
- "book detail": add this as a separate menu entry on the taskbar option menu (and open dialog...). That seems doable. But that would make the already large row/context menu on the booklist screen even larger (and on a standard phone... having to scroll to see all options; not good).
- both list/detail screen: when tapping the checkbox (or using the row/context menu) bring up a dialog immediately. But as said above this defeats the point of a quick 'read' status change.
- ...

Regardless, I would of course add it to the "Settings / Field visibility" so users who don't need the field can hide it.

Not sure, any ideas on how you see an easy user-interface for it?

**Comment by PawelGu** [comment]
I thought about how the best implementation could look like, without knowing about Android programming restrictions/limitations regarding the gui.
You are right about the user experience. Menus and/or the interface itself shouldn't be cluttered or be unintuitive.

So either a field in the edit screen, or an - additional . number field (or slider?) on the book info screen (maybe at the top, with two arrows beside the slider to have fine grained control). It shouldn't be editable on the list screen.

So I would be happy if it is implemented anyways, thank you for considering :)

**Comment by tfonteyn** [comment]
I'm going to close this one. I still have a problem on how to cleanly integrate this in the UI, and I think it would be better if your e-reader software would provide synchronization between multiple devices. I think the need to manually edit the book in NTMB will prove to much of an overhead (for a user) anyhow.

**Comment by ngocanhtve** [comment]
> I still have a problem on how to cleanly integrate this in the UI,

Goodreads is the perfect reference for this feature, other than that I haven't seen any open source projects implementing it. If NeverTooManyBook implements it first, it will be the spotlight.

![](https://i.imgur.com/YESJrBQ.jpeg)
![](https://i.imgur.com/l802Vbg.jpeg)
![](https://i.imgur.com/rYaimgg.jpeg)

**Comment by tfonteyn** [comment]
this is good input. I'm re-opening this issue and will reconsider.

**Comment by tfonteyn** [comment]
to confirm.... I'm implementing this.

The plan is:

- have a preference whether the user wants to use a read/unread check (as currently implemented)
  or if the user wants to be able to set detailed progress.

- progress will be set-able on a per book-basis to percentage or page number.

- either will be editable from the "display-book" screen (and obviously from the "edit-book" screen) but NOT from the book-list (the context menu on the list is already far too long ....)

- first release of the progress editing will be simple... I can add sliders etc later

any comments so far are very welcome!

**Comment by tfonteyn** [comment]
@ngocanhtve  I'm getting close to finishing this. Could you please take care of the Vietnamese translation of the new strings? Either PR, or weblate, or even just copy/paste here, whatever is easiest for you :-)

**Comment by ngocanhtve** [comment]
> Could you please take care of the Vietnamese translation of the new strings?

Sure, i will

**Comment by tfonteyn** [comment]
a bit of a delay, but here is it finally:

[5.5.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v5.5.0)

Any issues or feedback/suggestions is always welcome, please log a new githib issue if needed.

**Comment by ngocanhtve** [comment]
> a bit of a delay, but here is it finally:
> 
> 5.5.0
> 
> Any issues or feedback/suggestions is always welcome, please log a new githib issue if needed.

It was working fine now.

**Comment by PawelGu** [comment]
Awesome! Finally I can keep up with reading on different devices.
It works great. Using the slider is fast and precise enough, thank you.

**Comment by ngocanhtve** [comment]
> Using the slider is fast and precise enough, thank you.

@tfonteyn Today I just started paying attention to being able to drag this progress bar, the animation is nice, the performance is good. Great! Thank again!
