### ISSUE TITLE
Dialog Size/Layout for Styles & Filter is wrong

### ISSUE THREAD

**Issue by Geo5** [tfonteyn/NeverTooManyBooks#17]
Hi, the sizes of the style-chooser and the filter dialogs are messed up/not working for me in portrait mode. In landscape mode they work fine.
See screenshots below for illustrations. Seems to be similar to #12 
App version is 4.4.1 Device is Google Pixel 6a
![IMG_20230608_232637](https://github.com/tfonteyn/NeverTooManyBooks/assets/18027367/aaf4810e-a4bb-4a99-bf3c-7104c7a5e6b7)
![IMG_20230608_232619](https://github.com/tfonteyn/NeverTooManyBooks/assets/18027367/e92b899c-3874-4122-9947-29ebdf50e37f)
![IMG_20230608_232600](https://github.com/tfonteyn/NeverTooManyBooks/assets/18027367/555b4810-49be-4d3f-a2fa-8cb69c1608f8)
![IMG_20230608_232536](https://github.com/tfonteyn/NeverTooManyBooks/assets/18027367/c7d08a46-58cd-4708-966b-c467475f62e8)
(Parts of the screenshots are cropped)

**Comment by tfonteyn** [comment]
Hi,

Yes - seems yet another issue with the 'floating dialogs' code I wrote on a bad day.

I think I have fixed it in [v4.4.2](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.4.2).
It's marked as pre-release but it's really just a regular release. Once you test it on your own device, I'll publish it.

**Comment by Geo5** [comment]
Hi, thank you for the quick fix!
It all works with the 4.4.2 version :)
