### ISSUE TITLE
 book listing style, I have enabled author and publisher, but only author is showing

### ISSUE THREAD

**Issue by tfonteyn** [tfonteyn/NeverTooManyBooks#19]
Split from #18 by @zettelmuseum

In my custom book listing style, I have enabled author and publisher, but only author is showing, maybe this is a bug?

**Comment by tfonteyn** [comment]
It depends what you mean.

When defining/editing a style, there are two things to note:

"Groups": these are the levels which will form the book-list nodes, with sorting applied.

"Book Details shown in the list": these are individual fields which will be shown (or hidden) for each book.

In other words:
- Having Author, Publisher as the "groups" will allow you to expand/collapse the list according to those 2 levels (with the 3th level being the book itself)
- Enabling "Publisher" on the "Book Details shown in the list" will always show the publisher on each book regardless whether Publisher was set as a group or not.

But aside of the above, The Publisher (but the same is true for any other field) will *only* be shown on the book level *if* the books actually has a publisher (i.e. if the search from internet websites returned a publisher.)

But let me know if I misunderstood the question of course.
When in doubt, create a backup and use an app which suport ZIP archives to open the backup file. Extract the "styles" and "preferences" and upload those here. Or just upload the entire backup if you wish. Either way I can look into it.

**Comment by zettelmuseum** [comment]
I'm talking about "book details shown in the list".
All the books have filled publisher fields.
I think the relevant json part is
style.list.show.fields : 6181
Please see screenshots.

![Screenshot_20230825-192720](https://github.com/tfonteyn/NeverTooManyBooks/assets/882338/ca17bb47-77d1-49c4-ae93-9b762b91b888)
![Screenshot_20230825-192638](https://github.com/tfonteyn/NeverTooManyBooks/assets/882338/09bf163a-32d8-48ed-9cc8-0f8d0a338748)
![Screenshot_20230825-192509](https://github.com/tfonteyn/NeverTooManyBooks/assets/882338/2224a94a-cac1-4816-9ea5-a75dd31aa1f6)
![Screenshot_20230825-194249](https://github.com/tfonteyn/NeverTooManyBooks/assets/882338/0a8aa4be-71e7-4cb4-bad0-3e2fed93f2b0)

**Comment by zettelmuseum** [comment]
Okay, I think I nailed the bug. (I deleted my previous comment)
I'm talking about "book details shown in list".
If I ONLY enable Publisher, it will not show in the list. If I ALSO enable Date Published, Publisher and Date Published show.
Should be easily reproducible.

**Comment by tfonteyn** [comment]
Brilliant find. It's indeed a bug, I found the issue and fixed it. 
I'll push a new release tomorrow (but will check your other issue first)

**Comment by tfonteyn** [comment]
Hi,

And here you go: new version [4.6.5](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.6.5)
