### ISSUE TITLE
adding books by title search, i get a book in a different language

### ISSUE THREAD

**Issue by tfonteyn** [tfonteyn/NeverTooManyBooks#20]
Split from #18 @zettelmuseum

sometimes when adding books by title search, i get a book in a different language. is there a way to specify language?

**Comment by tfonteyn** [comment]
Adding by title is not very reliable. Please use ISBN whenever possible.

Specifying the language for a search is currently not possible. A title-search will use whatever search-terms the website(s) support. The majority do not support language as a specific search field.

That said, can you give me the title and author + the list of enables websites and I'm happy to take a look and see if there is anything that can done to get better results.

**Comment by zettelmuseum** [comment]
I'm using the default websites config.
Example:
1.German Edition of Shuggie Bain by Douglas Stuart
German ISBN 978-3-446-27108-1
when I search by author, title I get the 
english one.
2. English Edition of Outsider by Stephen King
if I search by author, title I get the german one,
which is kind of funny.
So it is really random.

**Comment by tfonteyn** [comment]
Actually, for those two this is (well, as I coded it) predictable.

You see, "Shuggie Bain" is the exact same title in German and in English. The result returned is the first book found.

Same for "Outsider":  English title is "The outsider" but the German title is "Der outsider", so when searching for the title text "outsider", again the first one found is returned.

Returning the first result found is hard-coded.
I made provisions to allow returning multiple results and let the user choose which one to accept, but I simply never got around it to implement the latter part due to the fact that searching by ISBN works so much better anyhow.

Aside of the above, changing the order of websites searches will also influence the "first" result.

    I'm using the default websites config.

Take another look at the websites search order configuration. Go to "Settings/Websites" (or access the same from the options-menu on one of the search-book screens).
Each site lists how it can/will be searched.

For example:
    Amazon
    General; Shop
    (ISBN, Barcode)

Indicates that this site will be searched *only* by ISBN or barcodes (which in some obscure cases can be different from ISBN).
But:
    Google Books
   English and more; Catalogue
   (ISBN, Search)
Here we see this site can be searched by ISBN (actually valid for all sites) and by "Search". The latter is short for "Search by author/title". And yes, I fully agree I need to document this better. I think I'll add this info on the Search-by-author/title screen itself.

So in your two examples, you end up getting results from Google Books.

The solution is really to **always** use the ISBN. Scanning the barcode is the fastest in my opinion (also see the batch options to first scan a set of barcodes, and then at your leisure let the app search for the books and edit/save the results as needed.

Also: at the very least you should change the Amazon search to use the German website.
The [wiki/documentation](https://github.com/tfonteyn/NeverTooManyBooks/wiki) explains how to do this for first-time users. 

You just gave me an idea on how to make it easier for the user to configure individual websites like the Amazon one; I'll see to add this in the next feature release.

Obviously let me know if you need more details. I tend to expand the docs based on user questions :)

**Comment by zettelmuseum** [comment]
Yes this us buried quite deep in the settings, i didnt even dig that far. Is the wiki mentioned anywhere in the app? If it was in one of those pop ups...My bad. I tend to ignore them 😉

**Comment by tfonteyn** [comment]
Yes this is buried quite deep in the settings
I agree - it was far to obscure. I spend some time today on this and merged some options from the "More..." screen to the standard preferences + moved the website configuration to become a menu/action which can be done from the standard website selection list (it's simpler when you will see it ,as with me badly describing it here)

    Is the wiki mentioned anywhere in the app
Not in the app itself, but it is the 3rd line of the project readme 😁


    pop ups...My bad. I tend to ignore them 
I don't like them either;  they are more of a "let's hope someone reads them" and myself being slightly lazy about better documentation.

I've added the fix for #19 + an option to *show* the page-count on the list + the above preference improvement and added clarification notes to the "Search by title" screen.
I'll do some testing on my physical phone/tablet and push a new update; most likely tomorrow or Monday.
I'll let you know when done.

On #18 ... I'll keep it open for now and have a think.

**Comment by ngocanhtve** [comment]
> Please use ISBN whenever possible.

ISBN is almost a joke in Vietnam, most Vietnamese books cannot be found by ISBN.
