### ISSUE TITLE
Backup & export

### ISSUE THREAD

**Issue by Poringo** [tfonteyn/NeverTooManyBooks#21]
Hi,

Loving your app, specially the batch scan codes, I did not know I wanted that, easier to process a whole bookshelf.

Do the export functionality works? not sure if I am doing something wrong.

I am clicking on the button on the bottom right, and getting that error. Not clear what I do need to select or how.

I only have a couple books in a newly created bookshelf, if that matters.
Thanks!

[](url)
![Screenshot_20230831-161213](https://github.com/tfonteyn/NeverTooManyBooks/assets/1606168/eff4edc7-c8a2-4565-b622-fc7ca5075cbb)

**Comment by tfonteyn** [comment]
Hello,

Oh heck, yes - this is a bug... I can reproduce it easily. Must have slipped in between 4.5.1 and the latest version.

It's a rather late now today, but I'll fix it tomorrow and get back to you.

Thanks for reporting and your kind comments :-)
Tom

**Comment by tfonteyn** [comment]
ok - found it and fixed it...  part of the 4.6.0 release was optimization... and I goofed up.

I need to get some sleep now :)   but you can expect 4.6.6 tomorrow. I'll post a message here to update you.

cheers!
Tom

**Comment by tfonteyn** [comment]
and here you go:  [4.6.6](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.6.6)
