### ISSUE TITLE
Suggestion - grid layout

### ISSUE THREAD

**Issue by knightmob** [tfonteyn/NeverTooManyBooks#22]
Hello new user here! Nice app, a book tracker with google  books support, hell yeah! Just one suggestion for the better uniform appealing way of the app, pls add grid option, overall the ui seems neat and the design is okay.

Keep up the great work!

Oh just a heads-up, the external image custom support is not working, I keep click the missing image poster, but ot doesn't seem to prompt my file manager, that's all I bet

**Comment by tfonteyn** [comment]
Hello,

Thanks for the nice words 👍 

     pls add grid option
Can you please elaborate on what you mean?

    external image custom support is not working, I keep click the missing image poster
It's a long-click (tap-and-hold) , which will bring up a popup menu.

**Comment by ojppe** [comment]
With grid I assume he means a view option like this:

Edit: you might want to add a title field for books that don't have a cover

<img width="376" alt="mock" src="https://github.com/tfonteyn/NeverTooManyBooks/assets/77202355/c2f46331-38e2-43db-ba09-ffb2797a3ea1">

**Comment by tfonteyn** [comment]
oh - that's a nice idea - now why did I not think of that before.

It might take some time as I'm a bit busy in the next 2-3 weeks, but it'll get done. I like it.
But no promise on the timeframe - it's quite a fundamental change.

**Comment by knightmob** [comment]
> oh - that's a nice idea - now why did I not think of that before.
> 
> It might take some time as I'm a bit busy in the next 2-3 weeks, but it'll get done. I like it.
> But no promise on the timeframe - it's quite a fundamental change.

Oooh no hurry, the app itself is already stable, but thanks for reading my suggestion

**Comment by tfonteyn** [comment]
it'll be sooner then I thought. I've got it all working, but still needs some polishing :-)

**Comment by tfonteyn** [comment]
Just a quick update as I now have more time to work on it.
I'm fairly happy with what I have done (for a first release anyhow) but I need to tune the grid number of columns and cover sizes for different device screen sizes; it's a bit trial and error.

**Comment by tfonteyn** [comment]
[5.0.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v5.0.0) is now out.

Grid or List layout can be set on individual Styles.
So you can choose which Bookshelf/Style you want to see as a Grid or as the old List.

I'll add some extra notes to the [docs](https://github.com/tfonteyn/NeverTooManyBooks/wiki)  in the next couple of days as well.

I'm closing this issue, but if you find any issues or have other questions/enhancements requests, simply file new issues.

cheers!
