### ISSUE TITLE
Multiple errors and inability to clear out existing data

### ISSUE THREAD

**Issue by alogcat** [tfonteyn/NeverTooManyBooks#23]
This starts with an inability to edit books. I had a list I imported from Book Catalogue, which worked fine. When I try to edit a book, it crashes. At this point, the window that pops up has buttons that are very hard to see in a dark theme. When I go to send an email, it creates it and attaches the txt file, but doesn't populate an address to send to, so I can't send it. 
If I try to add a book, I can search by ISBN but it says searching on Amazon failed. However, it still brings me to the book page and it's correct. If I go to save it, it says "Please check that storage is writable, and has sufficient space." I know that I have tons of space remaining, and no issues writing from any other app. There is only internal storage, no SD card. 
I figured that if I uninstalled, I could try it new and import from Book Catalogue again. I did that, but it apparently remembers everything I had, so it's not even a fresh start? I try clearing data in Android settings before uninstalling, and it's the same result. The storage error occurs if I install an older version (which doesn't remember my books).

**Comment by tfonteyn** [comment]
oh boy - this sounds bad. Let's see what we can do.

First off, but I doubt it... this is not Android 14 I suppose? On android 14 there is a known issue for which I will have a fix in the next version.

Assuming it's not:

    When I go to send an email,
I presume this is on the dialog box after the crash? Yes, this bit is a 3rd party lib which does not seem to support "save to storage". Simply address the email to yourselves and/or manually store the attachment and upload it here on the issue.

On the other points:

    "Please check that storage is writable, and has sufficient space."
yes, I readily admit this error message can be misleading - it's really saying "can't write to the database". It's on my short-list to split this one into multiple more correct/exact messages.

    so it's not even a fresh start
Goto the Android system settings, and select "Apps" and navigate to the list of installed apps. Find this app, and open the details (depends on android version and device on how this is called and where exactly it is). I should have a line "Storage", click that and you should see a button "clear data" : this will clear ALL data related to the app. Careful!

    buttons that are very hard to see in a dark theme
I have seen this in the past, and I thought it was fixed. I'll have to check again. Meanwhile, goto "Settings" and set the Theme to "Light" as a workaround.

     if I install an older version 
Not supported, sorry. Database internals can/will change between versions and obviously I support upgrades, but not downgrades.

So, let's start with you reproducing it again : make it crash, select email, and  then save the email attachment temporarily and upload it here. 

     says searching on Amazon failed
Nothing specifically wrong here. There will be a number of different sites searched (see the option menu for selecting the ones you prefer). But in this case Amazon failed, and clearly another one succeeded.
As mentioned on the project page:
    WARNING: Amazon is increasingly blocking access. If you see any Amazon specific errors, I suggest you switch off Amazon in Settings/Search/Websites.

**Comment by alogcat** [comment]
Hi Tom,

As a matter of fact, it is Android 14. I will continue to use Book Catalogue in the meantime, and when I see a new version on Droid-ify, I will try that and look at renaming the bcbk to a zip as mentioned somewhere in the documentation. 

Thank you, and I love the app. It's so so useful for me.

**Comment by alogcat** [comment]
[NeverTooManyBooks-acra-report.txt](https://github.com/tfonteyn/NeverTooManyBooks/files/13073903/NeverTooManyBooks-acra-report.txt)
Here's the crash report from when I try to edit a book.

**Comment by tfonteyn** [comment]
oh - brilliant - if you allow me to :)

The report does confirm it's the known issue which means it's already fixed.  
If you're interested in the issue: see [this commit](https://github.com/tfonteyn/NeverTooManyBooks/commit/1201393949356b2c1efcb6963dc192466f1292a0)

I'm getting v5.1 ready for release any day now. It's basically bringing:
- global defaults for styles. i.e. it will allow to change the defaults as used by the builtin styles.
- tested and support for Android 14

> renaming the bcbk to a zip

It's not just a rename, check [this FAQ](https://github.com/tfonteyn/NeverTooManyBooks/wiki#importing-from-book-catalogue)

I'll keep this open, and let you know when 5.1 is out.

cheers
Tom

**Comment by alogcat** [comment]
Awesome, I will make a bcbk file when 5.1 is out, do the zip/file arrangement as noted, and then install and restore. I'm glad I still have Book Catalogue in the meantime, it's really such a handy tool, and I'm glad you forked it and made it reasonably forward-integrated!

**Comment by alogcat** [comment]
If I might make a feature request as well? The ability to either schedule backups on a regular basis, or when edited (though I realize this may need a sort of hourly checker or something so that it doesn't try to backup a million times if I'm editing a bunch at once) like Aegis. I have syncthing copy my backups away, and having them automated is so wonderful. If I could schedule it to create a backup at midnight if there were any unsaved edits since the prior midnight, that would be ideal (for me). If that's down the list, that's totally fine, I can make it part of my regular backup routine, but automation and scheduling is just bomb. Thanks!

**Comment by tfonteyn** [comment]
I've split off the RFE to #24 for easier tracking. You will need to subscribe to #24 to get updates.

**Comment by tfonteyn** [comment]
Just a quick update. 

Due to your bad experience with the "crash-code" I decided to make that part more user friendly.
The 5.1 release will now simply offer to save the crash-report to storage, and point users to this project website (the 'issues' tab) with better help/info on what to do. 

The rather too 'fuzzy' error message "Please check that storage is writable..." has been split/redone as well and will now be much clearer.

But of course, ideally you will never see either of those again... hehe ;-)

This is delaying the release a bit of course :(  but I'm getting there soon now.

**Comment by alogcat** [comment]
Fantastic, can't wait for the next version to drop!

**Comment by tfonteyn** [comment]
And here it is: [5.1.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v5.1.0)

**Comment by alogcat** [comment]
Hi Tom, 
You're fantastic! I backed up Book Catalogue, installed 5.1.0, performed the tar->zip, syncd it, and imported. All appears to be well again! Best to you!
