### ISSUE TITLE
Calibre not connecting

### ISSUE THREAD

**Issue by Humam-Hamdan** [tfonteyn/NeverTooManyBooks#25]
Hi,
i like the app, was surprised to know that there's a calibre connect option, so tried it, but it requests ajax, and in calibre there's no ajax, and there's no extension with that name either, so how to connect the app with calibre server?

**Comment by tfonteyn** [comment]
Hello,

Thank for your kind words :)

The app does indeed not connect to the desktop Calibre application as-such, but it can connect to a [Calibre Content Server](https://manual.calibre-ebook.com/server.html).

You can run such a server standalone (on some home-server as I do, or perhaps in the cloud) or temporary start one from the Calibre desktop program. The setup is a bit tricky, but once done it works pretty well. Take a look at the documentation for the  [Calibre Content Server](https://manual.calibre-ebook.com/server.html) first. 

Once you have it working and can access it from a browser on your phone, you can then start configuring this app.
Keep in mind this app is not a reader though, the Calibre connection is for synchronization of book-lists/info only.

I'll leave this question open until you have the CCS setup and working - I'm happy to help on the NTMB-to-CCS connection setup.

**Comment by Humam-Hamdan** [comment]
it seems like i didn't mention it, but i'm running it from the calibre desktop, and can open the library from my phone and from moonreader

**Comment by tfonteyn** [comment]
> can open the library from my phone and from moonreader
Can you elaborate on how you connect ?

What is the IP address and the port on which the CCS is listening?
And have you setup a user/password for remote connections in Calibre ?

**Comment by Humam-Hamdan** [comment]
i connect by inputting the ip adress into the url bar and then input the username-password
the ip is the one that calibre gave me (not the 127 port 8080(changed it)), and yes, i have set it up.
and yes, i only need the connection to get my metadata

**Comment by tfonteyn** [comment]
ok - then a connection should be possible.

Can you please attach a debug report?

First try a connection from NTMB and reproduce the failure.
Now go to "Settings", scroll to the bottom and pick "Maintenance". Then pick "Debug report".
Enable the 'settings' and 'logs' (no need for the db). You will be able to save it to your storage.
Next attach that file here. (and no worry, the password you have in there will be *** out).

for completeness sake, as I skipped this at first:

> requests ajax, and in calibre there's no ajax,

there is in fact. The CCS provides ajax access, badly documented, but have a look at [this Calibre source code](https://github.com/kovidgoyal/calibre/blob/master/src/calibre/srv/ajax.py)

**Comment by Humam-Hamdan** [comment]
[ntmb-debug-2023-10-27.zip](https://github.com/tfonteyn/NeverTooManyBooks/files/13193498/ntmb-debug-2023-10-27.zip)


here's the report.
made a system wide search and didn't find the ajax file (not even wizfile found it)

**Comment by tfonteyn** [comment]
> calibre.host.url=192.168.0.65:8090

You need to configure a URL, i.e.: 

    http://192.168.0.65:8090
or if you have secured it:

    https://192.168.0.65:8090
In the latter case, and if you use a self-signed certificate, you also need to upload the "CA Certificate" in the app.

> made a system wide search and didn't find the ajax file (not even wizfile found it)

well, it's certainly there on my installations. What version of Calibre are you using and on what platform?

**Comment by Humam-Hamdan** [comment]
Well, that's the ip I'm using
Also, im using a verion before .29, it was .28.1 or like that, on windows 10

**Comment by tfonteyn** [comment]
> made a system wide search and didn't find the ajax file (not even wizfile found it)

I didn't realise you were looking for the *actual* ajax file on your machine. That ajax 'file' is source code, which is compiled before use. It's "baked" in.

> Well, that's the ip I'm using

sure, but you entered the URL as being "192.168.0.65:8090" while you need to enter it as a **URL**.
So go into "Settings" and update the "Site address (URL)" field to

    http://192.168.0.65:8090

(or if secured, as per previous post). So **with** the prefix of "http://".

**Comment by Humam-Hamdan** [comment]
well, that explains why i didn't find it, lol.
just tried it, gave me
Cleartext HHTP traffic to 192.168.0.65:8090 not permitted

**Comment by tfonteyn** [comment]
ok - so far so good. As your android device is blocking unsecure traffic, you will now have to setup security.

Are you familiar with SSL and certificates? It's a bit beyond the scope here to give you a crash course, but if needed, just ask and I'll see what I can do.

You will need to use a tool like "openssl" or "keytool" or similar.
I do have a script to make it easy... but it requires a Java installation and a 'bash' environment: [gencert](https://github.com/tfonteyn/scripts)

- create a personal CA certificate (just use a bogus host name, but set the IP address as a subjectAlternativeName)
- from that CA, create a client certificate.

both of those should be in PEM format.

Once done, configure Calibre to use them:
- open Calibre preferences
- open "Sharing over the net"
- switch to the "Advanced" tab
- find "Path to the SSL certificate file" and upload the client certificate pem file.
- below that, "Path to SSL private key file": upload the personal CA certificate pem file.
- a good habit/reminder would be to adjust the port to 8443 but that's optional.
- restart the CCS.
- test from a browser accessing:   https://192.168.0.65:8443 (note the 's' in the protocol)
The browser will likely complain about the certificate. You can force it and/or import the personal CA certificate file as you prefer.

If all ok, open the NTMB app, go to the Calibre settings and:
- adjust the url to also be "https://192.168.0.65:8443"
- tap on "CA Certificate" and upload the same personal CA certificate pem file as above.

tap "back" and test the connection

edit: added info on subjectAlternativeName

**Comment by Humam-Hamdan** [comment]
i have java, bash? i have win terminal, does it work?
is there anythin else i need?

**Comment by Humam-Hamdan** [comment]
also, downloaded cygwin, what should i do with it?

**Comment by Humam-Hamdan** [comment]
oh, i also have linux subsystem, but without distro

**Comment by tfonteyn** [comment]
brilliant. Cygwin is fine (even just bash.exe + java is enough)

Make sure the "keytool" command from Java is on the path.

Lets assume you have Java sdk installed in "C:\mypath\to\java"

then in the cygwin/bash shell use:

    export PATH=/cygdrive/c/mypath/to/java/bin

I strongly suggest you create a new directory to run the below - it will generate a dozen files.

Download the "gencert.sh" into that directory, and run it with:

    ./gencerts.sh -s calibre -sip 192.168.0.65 -ca calibreCA

The first "calibre" is just a bogus hostname for the machine where you run Calibre, assuming you have no personal DNS setup :)
The "calibreCA" is just a generic name.
Both of the above names will be part of the filename(s) generated.

The -sip is obviously the IP address from the machine where you run Calibre.

(if you want to see exactly what the script does, add a -v on that command line; it's an educational script I once wrote; as such it does more than you need, but you can ignore the extras)

I suggest you keep the entire directory with generated files for future reference. If you ever need to change the IP address you will need to regenerate the client cert with the same gencert.sh command / new IP

The two files you need will be
- calibreCA.pem               -> the  personal CA certificate pem file.
- calibre.cert-chain.pem   -> the client certificate pem file (with full cert chain)

Import those files as described before.

**Comment by Humam-Hamdan** [comment]
gave me keytool error :)

**Comment by Humam-Hamdan** [comment]
gave me error 
line 620 -rm command not found
i know it's a remove but it doesn't seem like it's been recognized
removed everthing and re-ran, worked fine.

**Comment by Humam-Hamdan** [comment]
gave me another error
calibre, version 6.26.0
ERROR: Failed to start Content server: [SSL] PEM lib (_ssl.c:3883)

**Comment by tfonteyn** [comment]
"rm" is part of the "coreutils" in cygwin; and yes, I just use it to cleanup.

**Comment by tfonteyn** [comment]
oh heck.... sorry, I made a typo. The files you need to import into Calibre are:
- calibre.cert-chain.pem    as the certificate chain
- calibre.key.pem              as the private key file

The "calibreCA.pem" ony goes into NTMB (and in your browser if you want)

**Comment by Humam-Hamdan** [comment]
Error, connection reset (phone browser)

**Comment by Humam-Hamdan** [comment]
Network error, timedout

**Comment by tfonteyn** [comment]
silly question probably, but did you restart the CCS?

and can you try to connect to it from a browser on your windows machine first?
Make sure to enter the full url:

    https://192.168.0.65:8443

Obviously check the IP number and port to be what Calibre uses.
Check the Calibre "connect/share" menu to see the IP and port -> next to it should say HTTPS

**Comment by Humam-Hamdan** [comment]
> silly question probably, but did you restart the CCS?

Yep
> Obviously check the IP number and port to be what Calibre uses.

can access it from pc
and yes, it shows htpps

**Comment by Humam-Hamdan** [comment]
also moonreader can't access it anymore

**Comment by Humam-Hamdan** [comment]
a restart did the trick, lol.
thanks for the amazing app & support :)
if it's on the roadmap, a review section&template would be nice.
also, importing data from goodreads :>
