### ISSUE TITLE
Filter "Reading"

### ISSUE THREAD

**Issue by Humam-Hamdan** [tfonteyn/NeverTooManyBooks#26]
If possible, add the "reading" status to filter/sort when using the read/unread. It'll be when there's a start date but no end date.

**Comment by tfonteyn** [comment]
Basically, instead of groups "Read" and "Unread"... display  "Reading", "Read" and "Unread".

right? Yes, good idea I'll add it.

**Comment by tfonteyn** [comment]
Just to confirm:

I'll add this to the sorting Style "Read/Unread", i.e. to the Group as mentioned in my previous note here.

Adding it as a filter will have to wait for now, I'll put it on the todo list.

**Comment by Humam-Hamdan** [comment]
> Basically, instead of groups "Read" and "Unread"... display "Reading", "Read" and "Unread".

Yep, that's it, just seeing what i'm reading atm, filter isn't really that important (since i only use the app to track/instead of goodreads)

**Comment by tfonteyn** [comment]
I've implemented it just now, so it will be included in the upcoming 5.1 release... which is for any day now or at the latest next week.

**Comment by tfonteyn** [comment]
ah yes, and about Goodreads: they are part of the Amazon group since some years.... and disabled their API, so accessing Goodreads is no longer easy/possible. See [Goodreads API](https://help.goodreads.com/s/article/Does-Goodreads-support-the-use-of-APIs)

**Comment by Humam-Hamdan** [comment]
goodreads went to hell after amazon bought them.
Thanks!

**Comment by tfonteyn** [comment]
And here it is: [5.1.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v5.1.0)

This includes both the grouping as originally promised + the filtering as well.

**Comment by Humam-Hamdan** [comment]
Amazing, thanks for the update!
