### ISSUE TITLE
A "Review" section in the book viewer 

### ISSUE THREAD

**Issue by Humam-Hamdan** [tfonteyn/NeverTooManyBooks#28]
It'd be nice to have a section for reviews, and it'd be even nicer if the user could make a review "template" and choose from it (book, novel, for work, study, etc)

**Comment by tfonteyn** [comment]
Not sure how useful this would be. Typically reviews are something you want to share.
The only sharing option I have for now is the standard "Share" of a Book (currently limited to a sentence stating which book you're 'reading' which I admit is not even accurate).

I did consider allowing the add the "Personal Notes" fields to that share as well, but decided against it as (for myself at least) those notes are meant to be personal. I suppose I could revisit this and offer an option to add them when you're "Share" 'ing a book.

Can you elaborate on how you see this "section for reviews" used? By which I mean, what would not be covered by just writing your review in the personal notes section?

**Comment by Humam-Hamdan** [comment]
Just the personal notes in another tab in the book info, not anything fancy and certainly not sharable : )

**Comment by tfonteyn** [comment]
That's already there. On the tab "Notes", scroll down to the last field "Personal Notes" :)

**Comment by Humam-Hamdan** [comment]
Oh well, ok thanks, then just the template thing
also moving it to be under the rating and date start-finish.

**Comment by tfonteyn** [comment]
> moving it to be under the rating and date start-finish.

I had it higher up the screen before, but found that as soon as you have a bit of text in it, other fields are then off-screen.
So it's all a trade-off I'm afraid. I did briefly think of having it on its own tab, but that's 5 tabs then (or 6 if the site-id is switched on) and that is simply not usable.

>  template thing

Can you give an example?

**Comment by Humam-Hamdan** [comment]
For the template I'd say something like:
Main takeaway (one point only):

How the evetns pacing was (in case it's a story):

a detailed review (basically thought dump:


Something like that

**Comment by tfonteyn** [comment]
ah, just a text block - got it (multiple editable from a picklist I think you mean).

I'm going to decline, I think this would be used by very few people.

However, I've used text-substitution utilities on my laptop (if you're curious, [AutoKey](https://github.com/autokey/autokey) )and similar apps exist for Android.

Take a look at [SwiftKey](https://play.google.com/store/apps/details?id=com.touchtype.swiftkey).
I've not used this one myself, but from what I read it supports custom clips / text-substitution.
Once you get the hang of it,  text-substitution is a huge timesaver.

**Comment by Humam-Hamdan** [comment]
Ok, thanks for the amazing app : ). (I maily use obsidian for review but thought it might get in handy to have it on the app too, thanks anyways ;) .)
