### ISSUE TITLE
Crop cover left/right usable with Android 12+ gesture navigation

### ISSUE THREAD

**Issue by Zocker1999NET** [tfonteyn/NeverTooManyBooks#29]
When trying to crop a cover image left & right, one needs to swipe from the screen sides to the center. However, that is impossible on Android 12+ with gesture navigation enabled as then the back action is triggered instead.

This may be improved when cropping is possible either by pinching with two fingers as well or by allowing to swipe further from the center.

**Comment by tfonteyn** [comment]
ah good point, I hadn't enabled that option on my device yet.

> pinching with two fingers

good idea, I'll add this in the next release.

**Comment by tfonteyn** [comment]
and here you go: [5.2.1](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v5.2.1/NeverTooManyBooks-5.2.1.apk)

pinching is implemented in addition to the old 4 edges method + there is a small toolbar with a 'back' button.

Edit: replaced 5.2.0 by 5.2.1
