### ISSUE TITLE
More Translations

### ISSUE THREAD

**Issue by maverick74** [tfonteyn/NeverTooManyBooks#3]
Hello,

I would like the app to be translated into Portuguese (pt).

Is there a Weblate instance, a file or something like that where i can do the translation?

Thank you

**Comment by tfonteyn** [comment]
Hello,

You'd be very welcome to contribute.

I've created a copy of the English string resources at:

[Portuguese template](https://github.com/tfonteyn/NeverTooManyBooks/blob/dev/app/src/main/res/values-pt/strings.xml)

which contains some comments on what the strings are representing.

Initially it's probably the easiest to just download that file, and upload the result here.

Alternatively you'd need to fork the project, edit the same file, and then create pull-requests.
To test, you will need to edit
[build.gradle](https://github.com/tfonteyn/NeverTooManyBooks/blob/dev/app/build.gradle)
adding "pt" to

    resourceConfigurations += ["en", "en_GB", "de", "fr", "nl", "es", "it", "el", "ru", "tr", "pt"]

(eventually, we can then add Portuguese to the preference screen as well but that can wait for now.)

But use whatever is the easiest for you and I'll be happy to do the integration.

Please ask me for anything you need.

Would this be Portuguese /Portugal or Portuguese /Brazil?  (I'm assuming Portugal for now)

**Comment by maverick74** [comment]
It's for Portuguese-Portugal.

Some projects call it **Pt-Pt** while others just **Pt** (because it's the origin country of the language) and add BR to Pt for brazil (pt-br) and so on for all other countries.

that's why i didn't specified :)

I'll keep in touch regarding the translation (i'll download the file!).

Thank you for your help :)

**Comment by maverick74** [comment]
10.153 lines... I had the notion there would be a lot to translate.
But i was not expecting "that lot". XP

It will take some time (as i don't have much free). But i'll get it done :)

I would also advise (if you plan to gather more people around this) to eventually get some translation system such as [Weblate](https://weblate.org) (free and opensource) or [Transifex](https://www.transifex.com/) (free plan for opensource projects) as it's less "techie"

**Comment by tfonteyn** [comment]
hehe - yes, the project grew a bit over the last 4 years.

The xml file is divided in "regions" (they fold in Android Studio) more or less grouping the intended use. I also tried providing comments for each string.

Which reminds me:  any string label starting with "X_..."  are not in actual use for now.
So skip those obviously.

     10.153 lines

eh? the stringx.xml only has 1687 lines of which 730 actual strings (still a lot of course).

    Pt-Pt while others just Pt

I assumed so much, which is why I created "pt".

    weblate

good point - I'll look into it.

I've done all existing translations myself.
English, French, German and Dutch should be ok or close enough.

Spanish/Italian ... not so sure. I used google + I can read those languages a bit.
The others... google and I expect them to be rather cranky but heck, I tried :)

**Comment by maverick74** [comment]
> Which reminds me: any string label starting with "X_..." are not in actual use for now.
> So skip those obviously.

That helps! Thanks :)
Still, if you intent on using them in the future, i prefer to translate them right away.

> eh? the stringx.xml only has 1687 lines of which 730 actual strings (still a lot of course).

That's weird!
I'm using "**[notepad next](https://github.com/dail8859/NotepadNext/)**" 
![imagem](https://user-images.githubusercontent.com/14912461/226964038-f2aaa769-0954-4cc0-8a12-b23cc66a35e6.png)


but even using other editors such as Kate, for example, (except for the also-weird warning about a line with 16.509 char) I also get >10.000

![imagem](https://user-images.githubusercontent.com/14912461/226954949-43515d81-ae98-4ca2-ad40-9273bc853393.png)


So either i'm doing something wrong or i downloaded the wrong file... which brings me to the name: 
I've got a 

string**s**.xml

 instead of a 

string**x**.xml

Was that a typo? Or did i got the wrong file?


> good point - I'll look into it.

I've used both before, but i have to confess that the fact of Weblate is GPL attracts me a bit more



> I've done all existing translations myself.

Outch 8|

**Comment by maverick74** [comment]
Ah!!!

My mistake! 

I've forgot i have to get the RAW file, and not a direct download.

That's what i get for using weblate||transifex too much. I've only used _github-direct-files_ once before 
(soo... get ready for helping me sometime later). 

Edit: This is **a lot less** intimidating ahahaha (i can now say i've translated bigger things before ahahaah)

**Comment by tfonteyn** [comment]
:)

    Still, if you intent on using them in the future, i prefer to translate them right away.
leave them till last then - by then I might delete some/all

I've been playing with webflate this afternoon - looks promising.
The only bit that I either haven't figured out yet / find annoying is they seem to add line-break where I use \n.
In translated files I've kept all string single-line as I tend to sort the lines alphabetically now and then.

Webflate lets my play with it for 14 days - before then I will need to request a Libre license.
But don't let that stop you - anything you do before/if I go ahead, I will happily integrate manually myself.

Meanwhile... I was going to push a 4.1 release soonish which adds the context-menu to all/most lists (consistency with the main list) but I keep getting sidetracked by refactoring.

    (soo... get ready for helping me sometime later).
absolutely - my pleasure

cheers

**Comment by maverick74** [comment]
> is they seem to add line-break where I use \n.

hummmm in C++ \n is indeed used for a line break... if i recall correctly...

(yep... while i love it, i've not coded much lately...)

will be nice if you get it working :)

**Comment by tfonteyn** [comment]
well, I jumped the gun. It's more or less set-up on Weblate and I've send them a request for Libre Hosting.

[nevertoomanybooks on weblate](https://hosted.weblate.org/projects/nevertoomanybooks/main/)

I suggest you hold of starting any translation. When they hopefully approve, I'll empty the Portuguese string resource file so it will show up on Weblate as a clean template (instead of pre-populated with English)

**Comment by maverick74** [comment]
I've translated a few strings...

can you confirm it's working ok?

**Comment by tfonteyn** [comment]
It looks like it.
I committed your strings in weblate, pulled them into my project, push back... and all seems well in weblate :)

Just keep in mind that the Weblate instance has not been approved yet; but I'm online most days and will pull/push whatever you add quickly.

thanks!

**Comment by tfonteyn** [comment]
just wanted to let you know: weblate approved the project  :)
I'll be checking it regularly and certainly before each new release.

**Comment by maverick74** [comment]
Great news!!!


Thank you.

I'll be translating it as fast i can (depends on free time) :)

**Comment by tfonteyn** [comment]
Not to worry - when we reach a critical amount I'll add it "officially" and obviously give you credit on the read-me pages :)

**Comment by maverick74** [comment]
Done! :)

**Comment by tfonteyn** [comment]
WAAW :) Brilliant!

I've committed and pulled in the full set. I thinks there are now 3 things left to do:

I've used [https://en.wikipedia.org/wiki/Quotation_mark](https://en.wikipedia.org/wiki/Quotation_mark#Summary_table) to try and use the correct quotation marks for each translation. For Portuguese, that table shows    **«…»**   as the primary quotes to use , but that directional **"..."** are accepted as well. As you're the native speaker, what do you suggest I use? I can easily edit the language file for that myself.

I'm fiddling with some small issues (unrelated), and once I'm done with them, I will run the app in Portuguese and see if all text fits nicely on buttons and in other restricted spaces. I can then also make a beta build available for you to check.

Obviously I will give you full credits :)  What name would you like me to use:
- on the github readme:  just @maverick74 ? Or?
- on the app 'about' page?

and then I'll push 4.3 out :)

edit: one more thing:  I need a Portuguese writer's name for the example on sorting by Author name. Pick your favourite (or well known) local Author please :)

**Comment by maverick74** [comment]
sorry, I've took a bit to complete it...

about your questions:

1.
Quotation marks are definitely " "!
(«» are not seen much today, if there is anyone left still using it)

2.
about credits: No need for that! I made a "public domain" contribution (and beside, "John Maverick" naturally isn't my name. Just a "pseudonym" I use to make contributions)

3.
about authors... we have the well known Nobel prize José Saramago... but I honestly don't like him THAT much (I'm Catholic - LOL)... So I'll just recommend you to use Luís de Camões
( https://en.m.wikipedia.org/wiki/Lu%C3%ADs_de_Cam%C3%B5es ) - it's kind of Portuguese's Dante

**Comment by tfonteyn** [comment]
no worry :) I'm very grateful for your work :)

ok - then it looks like we're all done.

I've checked all screen layouts and the Portuguese text seem to fit just fine.
I've also added "pt" to the supported list, and to the app preference list.

I'm doing some final testing for a couple of (unrelated) issues and expect to push a 4.3 release with Portuguese  fully enabled in the next couple of days.

**Comment by tfonteyn** [comment]
Here we go :)

[v4.3.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.3.0)

Let me know if you see any issues of course.

Again, MANY thanks for your contribution!

**Comment by maverick74** [comment]
> Here we go :)
> 
> [v4.3.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.3.0)
> 
> Let me know if you see any issues of course.
> 
> Again, MANY thanks for your contribution!

You've developed it. You've done the hard work.
I've just translated something I'll be using for free.

It should be me thanking you. Ah ah ah ah.

By the way... 4.3 ain't loading. The screen just stays black. Better check it out!

**Comment by tfonteyn** [comment]
if you mean downloading from github.... they have been having issues all morning. 
Accessing the site  barely worked (even just the html part of the repo).

[https://www.githubstatus.com/](https://www.githubstatus.com/)

says it's ok again now. But from past experience, that depends from which ISP/Country you access them.

**Comment by maverick74** [comment]
> if you mean downloading from github.... they have been having issues all morning. Accessing the site barely worked (even just the html part of the repo).
> 
> https://www.githubstatus.com/
> 
> says it's ok again now. But from past experience, that depends from which ISP/Country you access them.

No. I've apparently been able to download the file and install it. Just when i press the icon to launch the app it just doesn't do anything.

**Comment by tfonteyn** [comment]
eek?

It worked fine here - I downloaded it from github straight onto my 2 physical devices and it installed and started/upgraded  just fine.
I also just tried a download and installed it into a emulator from new.

can you try downloading it on a pc/mac and reinstalling ?

I ran an md5 on a clean download:

$ md5sum NeverTooManyBooks-v4.3.0.apk
f2c6c9813b54d7bc3bdc8d1d0b294f26 *NeverTooManyBooks-v4.3.0.apk

**Comment by maverick74** [comment]
Hum... Funny!

I can't load any of the apks from github (from 4.1.2 - 4.3... :(

And now i can't find it on f-droid either...

**Comment by maverick74** [comment]
> can you try downloading it on a pc/mac and reinstalling ?

I got the same result... I tap it and nothing happens (i do get an entry for it on the android "task manager")

I believe the version i had was pulled from f-droid, but now i can't find it. Why was it removed?

**Comment by tfonteyn** [comment]
> f-droid

I wasn't aware that it was even there? I didn't add it there. It does make me wonder if an upgrade from such a version would create a problem. I have no idea how they build/copy?
I did recently (like I always do when uploading a new release) remove the 4.1.1 apk from github.
Was the f-droid version perhaps a mirror of that one?
I've also removed 2 stale/unused branches - but I doubt that has anything to do with f-droid at all.

- If you have a recent backup, I would suggest totally removing the app, and do a clean install and import the backup.
- If you don't, then I can perhaps create a special build to see what's going on assuming that some sort of startup is done.
- If you have rooted the device, then we should be able to get the log file for a sanity check, and recover the "nevertoomanybooks.db" file and the cover files. They are all in the standard subdirectories of the app internal data folder.
- I'll have a think what else is possible, but nothing was changed lately in the startup code either. The 4.0.0 release was the most recent database update.

**Comment by maverick74** [comment]
> * If you have a recent backup, I would suggest totally removing the app, and do a clean install and import the backup.

i never went on to fill any data to the app and, as such, never created a backup

> * If you don't, then I can perhaps create a special build to see what's going on assuming that some sort of startup is done.

maybe a solution...

> * If you have rooted the device, then we should be able to get the log file for a sanity check, and recover the "nevertoomanybooks.db" file and the cover files. They are all in the standard subdirectories of the app internal data folder.

I don't have a rooted device and i can't find anything with the name *nevertoo*, beside the apk that i just downloaded

> * I'll have a think what else is possible, but nothing was changed lately in the startup code either. The 4.0.0 release was the most recent database update.

I can't say for sure that i got it from f-droid. But i bet on it! I usually don't get much things from the play store as i usually don't get apk directly from github... so the only options are f-droid or maybe izzyondroid repo (which i experimented recently)

**Comment by maverick74** [comment]
> or maybe izzyondroid repo

most probably izzyondroid repo!!! It's listed here as version 4.2

try to search for "books"

https://apt.izzysoft.de/fdroid/index.php

**Comment by tfonteyn** [comment]
> izzyondroid 

never heard of that site; but you're right, they do have a copy of 4.2 - even with screen shots.

https://apt.izzysoft.de/fdroid/index/apk/com.hardbacknutter.nevertoomanybooks

**Comment by tfonteyn** [comment]
ah - cross-post :)    let me do a download of that version and see if I can install it from scratch, then upgrade it to 4.3

**Comment by tfonteyn** [comment]
that went ok.
I pulled their 4.2 down and installed it on a clean emulator. Started it, added a book.
Then dropped the 4.3 apk on that emulator; it upgrade fine. Started it, and all was fine.

I ran sha crc's on both their 4.2 and my own 4.2 build, and the checksums are identical.

> i never went on to fill any data to the app and, as such, never created a backup

then I would definitively try fully removing and a clean 4.3 install. If that fails, then I'll create a debug build for you.

**Comment by maverick74** [comment]
I have removed it multiple times and so far no luck.

Also, i've tried every versions of the izzyondroid repo and, now, i can't get any to run either.

I'm going to remove, search any references on the android directory and reboot the phone and try again

**Comment by maverick74** [comment]
No! 

Still doesn't load!

(and i can't, honestly, spend more time with it now... )

I'm  on android 8.1, if that helps...

**Comment by tfonteyn** [comment]
my own physical phone is an android 8.0 which as I said installed just fine. My tablet is on 12, and I test on emulators with 8.0, 12 and 13. So it's got to be something really specific to yours. 

The weird things is that it has worked before as you said.
My first question in such a situation (I worked in IT enterprise support) is : "what changed?" - is there anything whatsoever which was changed on your device since it last worked? 

I'll prep a debug build for you.  Could take me a couple of days as I want to look at as many angles as possible and force possible failures here.

**Comment by maverick74** [comment]
> I'll prep a debug build for you

Wait. Before you get to all that work let me try a few things first (that may take me a few days).

I originally though it was some compilation error,  but we already discarded that... So... Let me try a few things and if I can't figure it out then you prepare that debug version :)

**Comment by tfonteyn** [comment]
It's less work than you think :)

[debug version on OneDrive](https://1drv.ms/u/s!Aify9sSvzXtjgS7n5-Jg5w9QIwVX?e=Wcc99S)

Due to being debug, its quite large, 10 MB.

Important: the app id is different from the normal release, so it will (I hope) install as a different app, but with the same name!
I propose you remove again the original, and only install this debug one.

The main thing I added specifically for your test is a catch-all during startup. If the startup throws an error, then it **should** show a dialog box with the error. Do NOT click "ok" yet.
When that dialog shows, the message will already have been copied to the clipboard. First switch to an app where you paste it temporarily. If the next bit below fails, then at least you can copy/paste that message here.

Then switch back to the dialog and click "ok" - if things go well, you will end up on the maintenance screen where you can generate a debug report. This should then generate a file which will contain the full logfile (including the above message)  which you attach here.

If the whole thing just starts normally or does not show any dialog, we'll have to dig deeper :(

I suggest you remove the debug version afterwards.

**Comment by maverick74** [comment]
Sorry for the late reply.

Just tried it. It behaves like the release version (it does not start)!

I press the icon (it does the effect of getting pressed) and then I get nothing!

Task manager however shows the app running as shown on the screenshot

![Screenshot_2023-04-26-23-05-21-287_com android systemui](https://user-images.githubusercontent.com/14912461/234714084-3d5571c0-d8b1-42a1-8ce9-26255a18cdd9.jpg)

I'm out of clues about this... :)

**Comment by tfonteyn** [comment]
I'm away for a while, so replies will be slow I'm afraid.

It's very weird that the debug version (with a different app-id) behaves the same. So maybe there IS something about how it's compiled (but thinking aloud.... it works on my 8.0 device).

The only thing right now I can suggest is to deep clean up the app (both normal+debug) - although you might have already tried that?
A fairly good description is [https://www.androidcentral.com/how-and-when-clear-app-cache-or-data-android](https://www.androidcentral.com/how-and-when-clear-app-cache-or-data-android)
First kill the app, than make sure to clean BOTH the storage and the cache of the app,. Now simply try to start it again.
If this also fails, I'll see what I can do in building a version with live-logging (i.e. each startup step sending a line of text to the log) but that would have to wait until I'm back home.

**Comment by maverick74** [comment]
> The only thing right now I can suggest is to deep clean up the app (both normal+debug) - although you might have already tried that?

yeah... i've tried that!!! Didn't work...

(Now... what i didn't try was opening a hole on my phone!!! But i'm considering it! There are a good drillers campaign now!!! eheheheh - joking, naturally)

I'm out of ideas... But there's no hurries.
Specially if you're on holidays or something like it (i'm needing vacations for sure!)... so... forget about this and deal with it when you feel like it! :)

take your time :)

**Comment by tfonteyn** [comment]
yeah, I thought you would have tried that already :(

I'm sort of on holidays but I keep working on this app as it's a hobby anyhow. Only thing I can't do due to bandwidth limitations is upload large files. I have however already added new code to deal with **all** exceptions (if this means anything to you: I extended my use of the setUncaughtExceptionHandler method to call ACRA) which should allow us to get a debug dump. If I have a chance to get an upload done while at a friends place, I'll let you know.

thanks for your patience :)

**Comment by tfonteyn** [comment]
finally some good news ! I've found the issue which was related to the Locales (device language) being enumerated during startup.

So, please install [v4.3.1](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.3.1) and it should work as expected.

**Comment by tfonteyn** [comment]
I've removed the 4.3.1 in favour of adding a fix for #8.

So, please install [v4.3.2](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.3.2) and it should work as expected.

**Comment by maverick74** [comment]
YES!!! IT WORKS!!! 👍 

Either 4.3.1 (that came from F-Droid's IzzyOnDroid) or 4.3.2 that I installed manually after do work wonderfully!

THANK YOU!!!

I can finally start putting some order in my books :)

You can close this issue if you wish!

(and please... Consider adding this great app to F-Droid repo)

**Comment by tfonteyn** [comment]
glad to hear this :)

4.3.1: ouch.... that version had an embarrassing bug with the "table-of-content" which is why I pulled it the same day.

    Consider adding this great app to F-Droid repo

I briefly looked into doing that - I created their yml file, but need to tune it before uploading.
