### ISSUE TITLE
why does the app need android.permission.READ_CONTACTS?

### ISSUE THREAD

**Issue by IzzySoft** [tfonteyn/NeverTooManyBooks#33]
I just saw the app requests `android.permission.READ_CONTACTS` – but neither the app description nor the README gave me a clue what for that would be needed. Could you please clarify? Thanks in advance!

**Comment by tfonteyn** [comment]
It's completely optional. It's only used for the lending functionality.

If you lend a book out, you either type a name, or select one from your contacts.

But you don't have to grant the permission if you don't want/use that.

     README
Very good point! I'll add a note explaining this.

**Comment by tfonteyn** [comment]
I've added information to the [FAQ](https://github.com/tfonteyn/NeverTooManyBooks/wiki#android-permissions)

**Comment by IzzySoft** [comment]
Ah, a lending feature. So I guessed right (just didn't find it mentioned). Thanks, adding it to the allow-list for your app then (done)!

**Comment by IzzySoft** [comment]
PS: May I suggest establishing Fastlane structures for metadata (app description and graphics; Fastlane is the de-facto standard for that nowadays)? I could offer a PR with what is set up in my repo, so you could simply build on that (be welcome to my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for reference). That way you'd be in control of how your app is presented, and keep description/screenshots matching the latest releases (so such things won't be missed as easily because description outdates).

**Comment by tfonteyn** [comment]
I added [app.id.yml](https://github.com/tfonteyn/NeverTooManyBooks/blob/dev/metadata/app.id.yml) but never submitted it.

I presume Fastlane is in addition ? And it would make it easier for you to update the repo? Then by all means submit a PR and I'll complete it.

Thanks!

**Comment by IzzySoft** [comment]
> I added [app.id.yml](https://github.com/tfonteyn/NeverTooManyBooks/blob/dev/metadata/app.id.yml?rgh-link-date=2024-01-15T11%3A58%3A40Z) but never submitted it.

That's something different. The YAML lives in the `metadata/` of an F-Droid repo and is managed/maintained there.

> I presume Fastlane is in addition

It's even something different, see the link I provided. Or wait for my PR, which I'll now prepare, as:

> And it would make it easier for you to update the repo?

Definitely! Those files would be checked whenever a new release is being pulled, and changes/updates to it would then be pulled along.

> Then by all means submit a PR and I'll complete it.

Will do, preparing it now.

**Comment by IzzySoft** [comment]
There you go!
