### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by saltsoftdrink** [tfonteyn/NeverTooManyBooks#35]
On next update focus on UI it feels really bad in this UI also add material themed menus and avoid a loading screen pops up

**Comment by tfonteyn** [comment]
Please clarify what exactly is "bad" ? I'm always eager to improve, but you'll need to explain.

    material themed menus
All components/style used is Material3. Can you provide an example of these menus which you say are not?

    avoid a loading screen pops up
Again not sure what you mean. Do you mean the splash screen at start-up? If you do: the spash screen is part of the Android [guidelines](https://developer.android.com/develop/ui/views/launch/splash-screen) but without animations (I generally find animations a waste of cpu-time). It also serves as a progress dialog for when a background task is doing maintenance work at startup as well as more complex database upgrades which happen from time to time.

**Comment by saltsoftdrink** [comment]
> Please clarify what exactly is "bad" ? I'm always eager to improve, but you'll need to explain.
> 
> ```
> material themed menus
> ```
> 
> All components/style used is Material3. Can you provide an example of these menus which you say are not?
> 
> ```
> avoid a loading screen pops up
> ```
> 
> Again not sure what you mean. Do you mean the splash screen at start-up? If you do: the spash screen is part of the Android [guidelines](https://developer.android.com/develop/ui/views/launch/splash-screen) but without animations (I generally find animations a waste of cpu-time). It also serves as a progress dialog for when a background task is doing maintenance work at startup as well as more complex database upgrades which happen from time to time.

You may take a look at this app https://github.com/mateusz-bak/openreads-android

**Comment by tfonteyn** [comment]
again, I'm always eager to improve, but you need to give details on what you find "bad"?

    openreads
Sure, I'll take a look. "menu" ? maybe you mean the bottom-bar navigation? I'm only guessing - feel free to clarify what you mean?

Look, with respect, but unless you give specific examples, information on what precisely you want me to improve, not much I can do.

**Comment by saltsoftdrink** [comment]
> again, I'm always eager to improve, but you need to give details on what you find "bad"?
> 
> ```
> openreads
> ```
> 
> Sure, I'll take a look. "menu" ? maybe you mean the bottom-bar navigation? I'm only guessing - feel free to clarify what you mean?
> 
> Look, with respect, but unless you give specific examples, information on what precisely you want me to improve, not much I can do.

First off all add tabs like that for much easier grouping

**Comment by saltsoftdrink** [comment]
Ok, let's work together is there a way where we can communicate more efficiently? Any social media other than discord?

**Comment by tfonteyn** [comment]
Please write a clear description of what you think needs improvement and include details!

Example:  When you write "First off all add tabs like that for much easier grouping" you need to specify things like:
- what screen(s) ?
- group what?
- group how?
- why ?

Unless you can write a detailed description of what you consider "bad" and how/where you would like to see improvements, there is not a lot I can or will do.

If English is not your first language, then feel free to write in French, German, Dutch or even Italian/Spanish (and at a stretch Swedish) and I'll happily take another look.

**Comment by saltsoftdrink** [comment]
> Please write a clear description of what you think needs improvement and include details!
> 
> Example: When you write "First off all add tabs like that for much easier grouping" you need to specify things like:
> 
>     * what screen(s) ?
> 
>     * group what?
> 
>     * group how?
> 
>     * why ?
> 
> 
> Unless you can write a detailed description of what you consider "bad" and how/where you would like to see improvements, there is not a lot I can or will do.
> 
> If English is not your first language, then feel free to write in French, German, Dutch or even Italian/Spanish (and at a stretch Swedish) and I'll happily take another look.

Since I'm on phone I can't attach images in GitHub please try another way to communicate so I can show you all the stuff I've made to improve the app

Thank You ❤️

**Comment by tfonteyn** [comment]
I'm going to close this request now.
If/when you can provide a written proposal (or upload images) as I asked for several times now,then feel free to create a new issue (but *with* details)

**Comment by saltsoftdrink** [comment]
> I'm going to close this request now. If/when you can provide a written proposal (or upload images) as I asked for several times now,then feel free to create a new issue (but _with_ details)

Man read my last reply I'm requesting for a platform to communicate

**Comment by saltsoftdrink** [comment]
@tfonteyn ☝️
