### ISSUE TITLE
Vietnamese Localization

### ISSUE THREAD

**Issue by ngocanhtve** [tfonteyn/NeverTooManyBooks#40]
Hello,

The Vietnamese translation is 43% done by hosted.weblate and it seems like you won't merge it until it reaches 100%. 

This is extremely unusual. But if you want something 100% perfect like a German often want, would you accept a full localization PR? I'd rather translate the whole strings and do PR than work hard on the weblate!

**Comment by tfonteyn** [comment]
Hello,

Firstly: many thanks for starting the translation - I really appreciate that :)

I was going to wait until some 80% was translated. To be fair, there was a Chinese (and even a Faroese) translation started and the volunteer sadly dropped out. I want to avoid presenting a half-complete translation.

Doing a PR would absolutely be very welcome.

The current Vietnamese strings have all been merged at "app/src/main/res/values-vi/strings.xml" (feel free to re-order the stringany way you like btw)
and the original English can be found at "app/src/main/res/values/strings.xml".

Don't bother with the string whose name starts with "X_". Those are not in use for now.

I'll make some time later tonight and upload a new version including the Vietnamese support. I'll let you know here when done.

And I'm very happy to add your name to the readme/about if you like; to give you full credit for your work.

Many thanks
Tom

**Comment by ngocanhtve** [comment]
Thank you! I will complete the strings.xml and make a pull request soon. Btw, could you please do not merge the existing Vietnamese strings? Because I will retranslate the entire English strings. I don't want you to waste your time merging it two times.

**Comment by tfonteyn** [comment]
I had merged those strings as/when they became available. No worry though, feel free to handle it whatever way works best for you.

**Comment by tfonteyn** [comment]
I've pushed a [5.3.2](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v5.3.2) with the current set of "vi" strings.

If you like you can do partial PR's and I can do quick pre-releases for you to test.
Just let me know and I'll try and accommodate you as much as possible :-)

btw, in the English text you will find (4 strings) with the author "Connie Willis". Please use your own favourite Vietnamese author. The name is used as an example.

many thanks!

**Comment by ngocanhtve** [comment]
I have completed the entire translation. Follows very closely the format of the English string. Includes retention of instruction notes \

**Comment by tfonteyn** [comment]
This is brilliant 👍 

I've merged the strings now. Please be patient as I'm rather busy this week, but I'll try to check things like string-length versus screen-space as soon as I can and try to release quickly.

Please let me know how you would like to be credited for your work on the readme page?

**Comment by ngocanhtve** [comment]
> but I'll try to check things like string-length versus screen-space as soon as I can and try to release quickly.

Take your time!

> Please let me know how you would like to be credited for your work on the readme page?

Feel free to use my github username. Both translations on hosted.weblate are also the same account logged in with github.

**Comment by tfonteyn** [comment]
I found one potential/minor issue:

Please correct me if I'm wrong of course, but I think Vietnamese does not use "articles" in its grammar.

The reason I'm asking is that NTMB optionally reorders titles depending on how the user wants to sort them
(NTMB handles this internally both for "showing" and for "ordering" titles)

For "ps_show_titles_reordered_on", you wrote:

> Chuyển bài viết hàng đầu xuống cuối,\nv.d. “Chúa tể của những chiếc nhẫn, The

In English:
"The Lord of the Rings" ->  in an ordered list, it will show under "T"
"Lord of the Rings, The" ->  in an ordered list, it will show under "L" which is where users usually want it.

I *think* that Vietnamese does not generally use this based on your translation of 
"The Lord Of The Rings" -> "Chúa tể của những chiếc nhẫn"

**Comment by ngocanhtve** [comment]
Exactly. But I really don't know where to hide the article "The" in the Vietnamese translation. Please suggest me a solution.

**Comment by tfonteyn** [comment]
Excellent. No worry at all. You had set

pv_reformat_titles_prefixes:  một|Một|một|Một|the|The

The only thing I need to do is set it to "|" and the code takes care of it automatically.

I do need you to translate this sentence please:

    "Only applicable to languages that use articles. English example: \"The Lord of The Rings\""

The part "The Lord of the Rings" needs to stay in English.
(it makes sense when you see this in the app's settings)

google tells me to use:

    Chỉ áp dụng cho các ngôn ngữ sử dụng mạo từ. Ví dụ tiếng Anh: \"The Lord of The Rings\"

Is that correct/good?

cheers!
Tom

**Comment by ngocanhtve** [comment]
> google tells me to use:
> 
> Chỉ áp dụng cho các ngôn ngữ sử dụng mạo từ. Ví dụ tiếng Anh: \"The Lord of The Rings\"
> 
> Is that correct/good?

It's correct, use it. Thank you very much!

**Comment by ngocanhtve** [comment]
Just updated with a PR!

**Comment by tfonteyn** [comment]
and it's live [5.4.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v5.4.0)

I've tested it for any obvious screen-space issues and it looks file.
Should you come across anything that does not look ok, just log an issue to let me know and I'll gladly take a look.

Many thanks for your contribution!

**Comment by ngocanhtve** [comment]
It looks great now. Thanks for your great work!
