### ISSUE TITLE
app crashes after update

### ISSUE THREAD

**Issue by thymaro** [tfonteyn/NeverTooManyBooks#43]
I have had several updates sin e the öast time I opened the app, because I haven't had time to make use of it lately, even though I wanted to. Anyways, after the most recent update, I tried to open the app and it was not possible, althpugh it led me to the settings for maintenance, where I was able to extract the attached log file. Maybe you can do something useful with it. 
[ntmb-crash-2024-04-15T07_20_05.309.txt](https://github.com/tfonteyn/NeverTooManyBooks/files/14974344/ntmb-crash-2024-04-15T07_20_05.309.txt)

**Comment by tfonteyn** [comment]
ouch.... this is a repeat occurrence of #30 

I'll fix this permanently and upload a new release later today. I'll let you know here.

**Comment by tfonteyn** [comment]
and done  - very sorry about this one :-(

Please install [5.5.1](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v5.5.1/NeverTooManyBooks-5.5.1.apk) on top of what you have now.

I'll keep this open, but I'm confident all will be well.

**Comment by thymaro** [comment]
All is well.
