### ISSUE TITLE
[Feature request] Book statistics

### ISSUE THREAD

**Issue by ngocanhtve** [tfonteyn/NeverTooManyBooks#45]
I just figured if the app can manage book lending, I need to see which books are lent out the most or which books are not lent out.

In general, statistics on all aspects related to books such as the number of pages read per year/month/day. Number of books lent by year/month/day.. The thickest or thinnest book.

So the statistics could be in one of the tabs in the bottom bar that I mentioned in the previous issue, for example 😁

Thank you!

**Comment by tfonteyn** [comment]
This is one for the backlog.

> see which books are lent out the most or which books are not lent out.

That should be fairly easy to add.

>  statistics on all aspects related to books

That would be a lot of work for which I currently don't really have the time for. But I'm not going to say "no" right now. I'll revisit this at a later date.
