### ISSUE TITLE
Add website to search

### ISSUE THREAD

**Issue by ojppe** [tfonteyn/NeverTooManyBooks#5]
Is it possible to add [bol.com](bol.com) to search ISBN, barcode and cover?

Would be of huge help

**Comment by tfonteyn** [comment]
I can certainly have a look if it's feasible, but is there anything specific which is not covered already by KBNL and the other generic  sites ?

**Comment by ojppe** [comment]
I don't see KBNL? (v4.1.1) are you adding it? That would be a great source as well. 
bol.com does have cover photos though.

**Comment by tfonteyn** [comment]
Well, it should have auto-enabled KBNL (was added in v4) when the phone is running in Dutch.

Open 'instellingen', select 'zoeken': 'websites' and you can enable/disable + change priority of sites by moving them up/down

LastDodo/StripInfo/Bedetheque:  comics
ISFDB: science-fiction, fantasy etc...

I strongly suggest you only enable the ones you need - it's faster :)
(you can access this page from the individual 'search' screens as well using their option menus)

Switch the "omslagen" tab to enable KBNL there as well.
And indeed, KBNL does not have cover pictures, but I probe the Belgian library website for those.

Also:  'instellingen', select 'zoeken': 'Meer'  where you can change some websites settings, among which the amazon one to use. You likely want to use amazon.nl

Sorry - I really need to add this sort of info to the docs :\

Still, I might have another look at BOL anyhow as I expect Amazon to become more and more difficult... (story for another time)

**Comment by tfonteyn** [comment]
oops... just found a tiny bug.. KBNL is indeed disabled by default; it SHOULD have been auto-enabled as described earlier.
Please just enable it as explained - I'll obviously auto-enable it in a future release.

**Comment by tfonteyn** [comment]
double-oops... just found a HUGE bug. I totally forgot to enable KBNL globally. This is embarrassing  :(

That will need a new release, I'll upload 4.1.2 later today.

**Comment by ojppe** [comment]
Haha, I was just about to reply I didn't see it altogether.
No worries :) I'll await the update.

**Comment by tfonteyn** [comment]
Well, here you go: [4.1.2](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.1.2)

You'll still need to enable KB.NL as it's an update though.

And a heads-up... I'll likely add BOL to a future 4.2 because "why not eh" :) It looks fairly easy to do so.
KB.NL does not always have the latest books.

So keep an eye on the release page.

cheers

**Comment by tfonteyn** [comment]
enjoy...

[4.2.0 with bol.com](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.2.0)

Don't forget to enable if needed as described earlier.

If you hit any problems, just log a new issue and I'll check.
