### ISSUE TITLE
(weblate) enable en@pirate on the weblate.

### ISSUE THREAD

**Issue by realeatham** [tfonteyn/NeverTooManyBooks#50]
I want to translate to pirate speak

**Comment by ngocanhtve** [comment]
Is it a real language?

**Comment by realeatham** [comment]
Not a spoken one, but a variation of english.

**Comment by realeatham** [comment]
I intend to translate the whole app if it is added

**Comment by tfonteyn** [comment]
Moahahaha :-)  Brilliant :-)

I think anyone with a user account on weblate can add a language. I have set no restrictions as far as I know.
I think you only need to go to the language tab on the project, and use the "+" sign top-left corner.

I'll only enable it  in a release when getting close to complete though.

**Comment by realeatham** [comment]
Users can only add basic languages, not ones with region codes. The code is specificly en@pirate , and it requires a maintainer to add it.

**Comment by realeatham** [comment]
If it didn't so many more apps would have it because of me lol

**Comment by tfonteyn** [comment]
I added it - I like a laugh 😂

**Comment by realeatham** [comment]
Thanks!

**Comment by ngocanhtve** [comment]
> I added it - I like a laugh 😂

You're a great dev, I didn't even think there existed a pirate language that was a variant of English. I thought to myself if NeverTooManyBooks was fully translated to it, who will be the ones using it? 😆

**Comment by tfonteyn** [comment]
@realeatham just a heads up: I pulled in your initial translation, and Android Studio and/or the build system does not like it.

It stated that "values-en@pirate" is not a valid resource directory name. I did try a rename to "values-en-pirate" but that fails with the same error.

Can you please find out what the correct (if any) resource name should be specifically on Android?

**Comment by realeatham** [comment]
Android is weird with languages, you can't add new stuff afaik. Try hd_US it is not used anywhere as far as I can tell

**Comment by tfonteyn** [comment]
I'm afraid I'm going to reject this before you put too much effort in it.

I would have liked to include it as it's fun, but it seems Android just does not support custom/made-up locale codes.
I tried finding some references, as I understand that some platforms actively support the pirate locale, but googling for tems with "android", "language","locale" combined with "pirate" just does not turn up anything useful.

I won't delete the weblate entries for now, just in case you find a solution.

**Comment by realeatham** [comment]
Yeah, android doesn't support it well. You should close this issue as not completed. I will see if there is a way to make suggestions to Google, but even if there is I would doubt a solution would come soon
