### ISSUE TITLE
[Feature Request] Improve grid view

### ISSUE THREAD

**Issue by ngocanhtve** [tfonteyn/NeverTooManyBooks#51]
**Is your feature request related to a problem? Please describe.**

Grid view has the corner of the cover image protruding from the outer border. Makes the visual experience not good.

**Describe the solution you'd like**

Increase the border-radius for the cover image to match the outer border.

**Describe alternatives you've considered**

Turn off the border-radius of the outer border so the grid view will be rectangular, matching the cover image.

**Additional context**

![](https://i.imgur.com/IK1ZzgN.jpeg)

**Comment by tfonteyn** [comment]
This is quite weird. Those rounded corners are far to big.

I don't do anything specific here, it's just using the system default which is "2dp"

This is how it looks out-of-the-box on my systems (physical + emulator):
![image](https://github.com/tfonteyn/NeverTooManyBooks/assets/2082710/e8ac6efc-ad19-4143-a995-54673c26ad54)

I have no idea how this could happen. The "2dp" value comes from the material library itself.
Is there maybe some screen-enhancer app active? 
Can you try this on another device?

What's your device brand/model? And what version of Android?

**Comment by ngocanhtve** [comment]
> Is there maybe some screen-enhancer app active?

No, I don't know about this kind of app.

> Can you try this on another device?

Okay I'll try tomorrow, 1 AM where I am right now.

> What's your device brand/model? And what version of Android?

Sony Xperia 1 mark I, Crdroid v9.15 (Android 13).

NeverTooManyBooks version: 5.5.3 (79)

**Comment by ngocanhtve** [comment]
> Can you try this on another device?

I tried on a Xiaomi device running Android 11, screen HD+, 6.22", 720 x 1520, ~ 270 ppi. The grids are like on your screenshot, symmetrical. 

My Sony device has a higher resolution, 6.5", 1096 x 2560, ~ 428 ppi, which will sometimes be run at 1644 x 3840, ~ 643 ppi.

I don't understand why on Sony the rounded corners are suddenly so big.

**Comment by ngocanhtve** [comment]
> Crdroid v9.15 (Android 13).

I think it's most likely due to the Crdroid ROM itself, which has many features of the Google Pixel, including having large rounded corners of apps in Recent App.

![](https://i.imgur.com/DctJdTW.jpeg)

Can you run the test on the Google Pixel device emulator?

**Comment by tfonteyn** [comment]
> Can you run the test on the Google Pixel device emulator?

That's what I use; I have several copies of if running different Android API versions.

But if this issue is really related to the Pixel and/or Crdroid then they do something bad really. 
You see, that corner radius comes straight from the Google material library which would mean they (pixel/crdroid) is overriding it.

I'll keep this issue open of course, but it will have to wait a bit before I can pursue.

**Comment by ngocanhtve** [comment]
![](https://imgur.com/32w7NhG.png)

This is the grid view on PixelOS ROM, look good. This means that the issue is not related Pixel or Pixel-look ROM at all, but in Crdroid's source code itself, they did something to the radius of the windows, frames in general.
