### ISSUE TITLE
Douban.com support

### ISSUE THREAD

**Issue by tfonteyn** [tfonteyn/NeverTooManyBooks#54]
Split from #14 

@CloneWith

@evoke322

Douban.com (Chinese: 豆瓣, [wiki](https://en.m.wikipedia.org/wiki/Douban) )is a Chinese online database and social networking service that allows users to record information and create content related to film, books, music, recent events, and activities in Chinese cities.

**Comment by CloneWith** [comment]
After some research, I've found an API maintained actively ([Doubanapi](https://github.com/kxy000/doubanapi)).

Douban uses OAuth 2.0 for access to the API. I'll provide more information if I could.

**Comment by CloneWith** [comment]
The API mentioned above is quite unstable and faces the risk of being banned by Douban official. So I consider it better to directly extract infomation from HTMLs.

Since it has a clear structure, I'll explain below with corresponding examples.

---

## Searching

We use `search.douban.com/book/subject_search?search_text=<Book>` for searching.

ISBN queries are usually more accurate, since there is only one result or none (if not found); Normal queries are also possible.

Taking a snippet from the original HTML file:

```html
<script type="text/javascript">
  window.__DATA__ = {<!-- JSON -->};
```

In this `window.__DATA__`, all entries are stored here, in JSON format.

```json
{
  "count": 15,
  "error_info": "",
  "items": [
    {
      "abstract": "\u8bfb\u5ba2\u6587\u5316 / \u51713\u518c / 2021\u5e74\u51fa\u7248",
      "id": 54985,
      "labels": [],
      "title": "[\u4e1b\u4e66] \u4e09\u4f53",
      "tpl_name": "search_simple",
      "url": "https://book.douban.com/series/54985"
    },
    {
      "tpl_name": "search_more",
      "urls": [
        {
          "text": "\u641c\u7d22\u66f4\u591a\u53eb \u201c\u4e09\u4f53\u201d \u7684\u4e1b\u4e66",
          "url": "https://book.douban.com/series/search?q=\u4e09\u4f53"
        }
      ]
    },
    {
      "abstract": "\u5218\u6148\u6b23 / \u91cd\u5e86\u51fa\u7248\u793e / 2008-1 / 23.00",
      "abstract_2": "",
      "cover_url": "https://img1.doubanio.com/view/subject/m/public/s2768378.jpg",
      "extra_actions": [],
      "id": 2567698,
      "interest": null,
      "label_actions": [],
      "labels": [],
      "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'2567698',query:'%E4%B8%89%E4%BD%93',i:'0',cat_id:'1001'})\"",
      "rating": {
        "count": 497838,
        "rating_info": "",
        "star_count": 4.5,
        "value": 8.9
      },
  "start": 0,
  "text": "\u4e09\u4f53",
  "total": 529
}
```

We don't use series, and we can rule them out first by searching for `series` in `url`s. Then for the remaining:

- `cover_url`: Link to front cover images
- `title`: Book title
- `id`: External ID
- `url`: Use if we need more information about the specific one
- `count`: Items shown per page. We can use this by adding `&start=<num>` in the request link
- `total`: Total items

## Book information

This is in `book.douban.com/subject/<ID>`. Tags are simply enough for us. Just extract values whose names match, in `<span class="pl">...</span>`:

- `作者`: Author(s)
- `出版社`: Publisher
- `出版年`: Date Published
- `页数`: Pages
- `定价`: List Price (Mostly CNY)
- `ISBN`: ISBN Number

And for `meta`s:

- `og:title`
- `og:description`
- `og:image`: Front cover
- `book:isbn`

---

Above is something I've just found by inspecting websites. Now we just need proper implementation in terms of code. Hope this helps!

**Comment by tfonteyn** [comment]
I think I get it. Your information is very useful and clear 👍 

Starting with https://search.douban.com/book/subject_search?search_text=9787536692930

I get a page with 3 results with an embedded JSON object with the 3 'items':

    {
        "count": 15,
        "error_info": "",
        "items": [
            {
                "abstract": "\u5218\u6148\u6b23 / \u91cd\u5e86\u51fa\u7248\u793e / 2011-6 / 23.00\u5143",
                "abstract_2": "",
                "cover_url": "https://img1.doubanio.com/view/subject/m/public/s34850048.jpg",
                "extra_actions": [],
                "id": 36874304,
                "interest": null,
                "label_actions": [],
                "labels": [],
                "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'36874304',query:'9787536692930',i:'0',cat_id:'1001'})\"",
                "rating": {
                    "count": 0,
                    "rating_info": "\u8bc4\u4ef7\u4eba\u6570\u4e0d\u8db3",
                    "star_count": 0,
                    "value": 0
                },
                "title": "\u4e09\u4f53",
                "topics": [],
                "tpl_name": "search_subject",
                "url": "https://book.douban.com/subject/36874304/"
            },
            {
                "abstract": "\u5218\u6148\u6b23 / \u91cd\u5e86\u51fa\u7248\u793e / 2021-1-1",
                "abstract_2": "",
                "cover_url": "https://img3.doubanio.com/view/subject/m/public/s34863232.jpg",
                "extra_actions": [],
                "id": 36892731,
                "interest": null,
                "label_actions": [],
                "labels": [],
                "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'36892731',query:'9787536692930',i:'1',cat_id:'1001'})\"",
                "rating": {
                    "count": 0,
                    "rating_info": "\u8bc4\u4ef7\u4eba\u6570\u4e0d\u8db3",
                    "star_count": 0,
                    "value": 0
                },
                "title": "\u4e09\u4f53",
                "topics": [],
                "tpl_name": "search_subject",
                "url": "https://book.douban.com/subject/36892731/"
            },
            {
                "abstract": "\u5218\u6148\u6b23 / \u91cd\u5e86\u51fa\u7248\u793e / 2008-1 / 23.00",
                "abstract_2": "",
                "cover_url": "https://img1.doubanio.com/view/subject/m/public/s2768378.jpg",
                "extra_actions": [],
                "id": 2567698,
                "interest": null,
                "label_actions": [],
                "labels": [],
                "more_url": "onclick=\"moreurl(this,{from:'book_subject_search',subject_id:'2567698',query:'9787536692930',i:'2',cat_id:'1001'})\"",
                "rating": {
                    "count": 497850,
                    "rating_info": "",
                    "star_count": 4.5,
                    "value": 8.9
                },
                "title": "\u4e09\u4f53 : \u201c\u5730\u7403\u5f80\u4e8b\u201d\u4e09\u90e8\u66f2\u4e4b\u4e00",
                "topics": [],
                "tpl_name": "search_subject",
                "url": "https://book.douban.com/subject/2567698/"
            }
        ],
        "report": {
            "qtype": "195",
            "tags": "\u8bfb\u4e66"
        },
        "start": 0,
        "text": "9787536692930",
        "total": 3
    };

Grab the 'url' from such an item, and I can get the book-details page.
The tags, as you say, are indeed fairly simple to get - coding will be identical to similar sites.

The one thing that seems to be difficult is the actual ISBN mapping to (in this example) multiple books.
9787536692930 is used for 3 different books (albeit from the same publisher)

In this example, the first one is a Paperback, from 2011. Second one is a Hardback from 2021, Third is another Paperback from 2008.

A (big) limitation in my app is that I only fetch ONE result. For sites which return more than one, I simply grab the first result unless I can (somehow) determine the "best" one to grab.

The cover can (after a search) be changed to one of the other editions; that's something I implement for other sites as well.

The other edition data is more difficult ... not impossible, but more work.

I'll experiment a bit more with some ISBN numbers and see what the options are.

**Comment by tfonteyn** [comment]
well, I have it all working. At least testing with two ISBN's is passing nicely.
Obviously I now need to create more tests to check for variations in the parsing of the results.

One such result is [https://book.douban.com/subject/36665775/](https://book.douban.com/subject/36665775/)

That book is a translation from French.
The author name is listed as [法] 保罗·霍尔特   ==>  [France] Paul Holt

Question: should I leave the author name as-is; so WITH the prefix of the country?
Or should I remove the prefix, so it becomes simply "保罗·霍尔特" ?

I'll probably have more questions like this later :)

edit: the two easy options are:
- remove the prefix, but you loose the information :(
- move it to the end of the name (and use round-brackets):  "保罗·霍尔特  (法)"
The latter would be my choice, as it would give proper sorting on the name and preserve the information.
The square-to-round brackets ...  parsing author names is very complex, and I already support a "(...)" section. I could add "[...]" if you think I should?

**Comment by CloneWith** [comment]
I think [法] is better, since it stresses the country which the author belongs to and may avoid misleading when the name is a bit vague (like duplicate names).
And it would be also nice to add a `country/region` property to authors, as a method to sort and group them.

**Comment by tfonteyn** [comment]
> I think [法] is better

just done exactly that :)

 [法] 保罗·霍尔特  becomes:   保罗·霍尔特 [法]   so sorting by name will work and the country/region information is still available.

>  add a country/region property to authors

I have wanted to do this for a long time. The problem is that up to now, **only** Douban provides this info. None of the other websites I search have this type of info available.
I could add it on the assumption that the user will have to set it manually... but that can be a lot of work for the user (I know I would not do it for my own collection, too many)

And a nice surprise: Douban also provide the "原作名" (original title) which is again the first time I have seen this done! Excellent.

Today I improved/extended parsing using some more examples with good results.
Not done yet, but it's looking good.

**Comment by tfonteyn** [comment]
A quick update to let you know what's happening.
This issue has been implemented and will be available in the upcoming 6.2 release.
But I'm still working on a small number of other enhancements/fixes which I also want in 6.2.
If things go as planned, you can expect 6.2 by next weekend.

**Comment by tfonteyn** [comment]
and here you go [6.2.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v6.2.0/NeverTooManyBooks-6.2.0.apk)

Many thanks for your initial research!

**Comment by tfonteyn** [comment]
I forgot to mention it (and sadly my public documentation is far from complete)

You can tweak the Douban lookups a little:

Goto Setttings/Websites, then from the option menu (top of screen right) the settings icon again to take you to the list of website .... and finally to Douban:

You can tweak how the search results should be ordered: either the first result found, or the latest book which was added to the Douban website... as I presumed that would also be the newest edition :)
