### ISSUE TITLE
[Feature Request] List & grid quick toggle button

### ISSUE THREAD

**Issue by ngocanhtve** [tfonteyn/NeverTooManyBooks#56]
Currently, each bookshelf will have to choose a view style of either list or grid. If i want to switch, i have to go to that bookshelf's settings to change, which takes a lot of operations.

Please add a button to toggle between grid and list on the home screen, so we can quickly switch between the two view styles regardless of which bookshelf we're in.

A button like that is very popular, please consider adding it to this great app.

Btw, good night :)

**Comment by tfonteyn** [comment]
Very good idea

I've added this just now.

Will be in the next release.

**Comment by ngocanhtve** [comment]
> I've added this just now.
> 
> Will be in the next release.

Great!
