### ISSUE TITLE
[Bug] Scroll bar issue

### ISSUE THREAD

**Issue by ngocanhtve** [tfonteyn/NeverTooManyBooks#57]
Dear, 

This time I discovered a small issue that I hope you have time to consider. 

![](https://github.com/tfonteyn/NeverTooManyBooks/assets/125894401/82082eb9-5713-4dad-bcbe-5fb8651d3cde)

The scroll bar (pill) is overlapping the book frame on the left. Can you pull the book frame a little further away to ensure aesthetics? Btw, Can you also radius the corners of the scroll pill? It will look softer according to the material design 3. 

And one more thing, leave only the scroll pill, I see the Google Sheet application only has the scroll pill left, the blurred background scroll bar at is cut off.

![](https://github.com/tfonteyn/NeverTooManyBooks/assets/125894401/705e4569-362a-4c73-9981-f72a75066ea5)

Thanks!

**Comment by tfonteyn** [comment]
hello,

> The scroll bar (pill) is overlapping the book frame on the left. 

fixed

> Can you also radius the corners of the scroll pill

done 
(ironically I was using the android material original, Google just is not consistent... oh well)

>  leave only the scroll pill

not sure about this. I'm a bit of a traditionalist when it comes to UI design. But I'll have a think.

I'm not going to do a release for these but they will be in the next one. 

I've been sidetracked to other projects, and I still want to look at the dynamic colour usage (new tests showed better results than my first impression). But I'll get back to you on that one soonish.
