### ISSUE TITLE
[Bug] Missing Resource Exception in Settings page

### ISSUE THREAD

**Issue by CloneWith** [tfonteyn/NeverTooManyBooks#58]
On version 6.0.0 when I navigate to the Settings page, the application always crashes, complaining unable to find `3-letter` language code for `zz`.

Below is the log file, might be of some help.

[ntmb-crash-2024-06-10T11_11_54.002.txt](https://github.com/user-attachments/files/15756039/ntmb-crash-2024-06-10T11_11_54.002.txt)

**Comment by tfonteyn** [comment]
I can't reproduce, so I will need to dig into this deeper.

first notes:

From crash file:

"ANDROID_VERSION": "12"
"SDK_INT": 31,
"SECURITY_PATCH": "2021-10-05"
"locale": "zh_CN_#Hans"
"userSetLocale": false

java.util.MissingResourceException: Couldn't find 3-letter language code for zz
  at java.util.Locale.getISO3Language(Locale.java:1742)
  at com.hardbacknutter.nevertoomanybooks.utils.Languages.createLanguageMappingCache(Unknown Source:53)
  at com.hardbacknutter.nevertoomanybooks.utils.Languages.getISO3FromDisplayName(Unknown Source:17)
  at com.hardbacknutter.nevertoomanybooks.utils.AppLocaleImpl.getLocale(Unknown Source:42)
  at com.hardbacknutter.nevertoomanybooks.settings.SettingsViewModel.init(Unknown Source:66)

  java/util/Locale.java:
    String lang = baseLocale.getLanguage();
    String language3 = ICU.getISO3Language(lang);
        if (!lang.isEmpty() && language3.isEmpty()) {
        // END Android-changed: Use ICU.
            throw new MissingResourceException("Couldn't find 3-letter language code for "
                    + lang, "FormatData_" + toString(), "ShortLanguage");
        }

so lang=="zz" comes from: baseLocale.getLanguage() 

In my tests, the Locale for  "zh_CN_#Hans" and the R.array.pv_ui_language values are all passing the above without a problem.


    private void createLanguageMappingCache(@NonNull final Context context,
                                            @NonNull final Locale locale) {
        final SharedPreferences cacheFile = getCacheFile(context);

        // just return if already done for this Locale.
        if (cacheFile.getBoolean(LANG_CREATED_PREFIX + locale.getISO3Language(), false)) {
            return;
        }
        final SharedPreferences.Editor ed = cacheFile.edit();
        for (final Locale loc : Locale.getAvailableLocales()) {
            ed.putString(loc.getDisplayLanguage(locale).toLowerCase(locale),
                         loc.getISO3Language());
        }

so we're crashing in either

     locale.getISO3Language()

or

    loc.getISO3Language()

The "locale" is "zh_CN_#Hans"  (the userLocale as coming from up the stacktrace)
So we must be crashing in the "loc"... which is coming from "Locale.getAvailableLocales()" and this is from the device OS.

**Comment by tfonteyn** [comment]
ok, I cannot be sure, but I think I can prevent a crash **if** my reasoning above is correct.
I'll create a "6.0.1" version for you to test with. I'll upload it later today and notify you of course.

**Comment by tfonteyn** [comment]
I uploaded [6.0.1](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v6.0.1)

It has protection against the MissingResourceException by doing a fallback from the iso-3 to an iso-2 code.

It's safe to install on top of the 6.0.0 and later release will install on top of this 6.0.1.

Please give this a try and let me know the results.

**Comment by CloneWith** [comment]
This version works properly. Thanks!

**Comment by tfonteyn** [comment]
it confirms the issue was in the OS as installed by the vendor. Good to know. Thanks for the feedback!
