### ISSUE TITLE
[Bug] English (US) issue

### ISSUE THREAD

**Issue by ngocanhtve** [tfonteyn/NeverTooManyBooks#59]
Dear,

When I select the app to display in English (UK), the app displays English. But I tried choosing the English (US), the app still displays Vietnamese.

https://github.com/tfonteyn/NeverTooManyBooks/assets/125894401/672bf9ae-b86b-4dfa-8337-a62da6f0e9c9

**Comment by tfonteyn** [comment]
I can't reproduce this one.

What I did:

1. emulator with Android 13
2. set system language to vietnamese; remove the original US english
3. start the app
4. displays vietnamese
5. settings/language, switch to French
6. Verify, all is French now
7. settings/language; switch to english US
8. open "Theme" where the word "color" is spelled in US spelling
9. back to settings/language; switch to english UK
10.  open "Theme" where the word "colour" is spelled in UK spelling

I tried some variations + all over again on an Android 11 emulator, but it keeps working here.

Try leaving the app and starting it again perhaps - although it certainly should not be needed.
This might be an issue related to the OS you run.

**Comment by ngocanhtve** [comment]
> emulator with Android 13

Try Android 14 because the issue on my device running Android 14. Btw, Thanks.

**Comment by tfonteyn** [comment]
nop - Android 14 same result, it all works here.

Can you list the steps you took (like I did in previous comment) ?  The mp4 you posted does not really show what you did.

**Comment by ngocanhtve** [comment]
I do not know. There's not much to do in display language setting. I just went there and tried to switch to US and as seen in the video.

**Comment by tfonteyn** [comment]
by coincidence when I was consolidating some language handling, I saw this happen.
The issue was that the Android Preference internal code was (I presume) caching.
It should be fixed in the next release.
