### ISSUE TITLE
[Feature request] Edit boxes

### ISSUE THREAD

**Issue by ngocanhtve** [tfonteyn/NeverTooManyBooks#60]
Dear, 

When editing info of a book. The original title and language selection boxes are not aligned like the other boxes.

![ResizedImage_2024-06-13_08-09-02_1310](https://github.com/tfonteyn/NeverTooManyBooks/assets/125894401/db66699d-b051-40c8-a056-13da17b3f785)

On the right side of the language box there is a large space, anyway, there is no use there for anything else, leaving it space looks unbalanced.

The original title box is also narrower than the boxes below.

**Comment by tfonteyn** [comment]
> original title box is also narrower

well spotted 👍 

> language box 

yes, wasn't ideal, the reason was partially because it's a fixed width field as was needed on tablet size screens.
But I agree.

both are fixed now for the next release
