### ISSUE TITLE
[bug] crash when editing first published date

### ISSUE THREAD

**Issue by coastgnu** [tfonteyn/NeverTooManyBooks#65]
While editing the date 'First Published' NTMB crashed

Book entry added by hand.
Weisband, Marina; Die neues Schule der Demokratie - Wilder denken, wirksam handeln; ISBN 9783103975925; S. Fischer Verlag; €(D) 22,00
[ntmb-crash-2024-06-16T11_48_37.368471.txt](https://github.com/user-attachments/files/15857290/ntmb-crash-2024-06-16T11_48_37.368471.txt)

**Comment by tfonteyn** [comment]
oh boy - not a good day :(

I've just finished the final fix for #64 

I'll check this one now

**Comment by tfonteyn** [comment]
found the issue and fixed it.

I'll spend some more time on testing the fix for #64, and then publish a new release. I'll let you know when it's uploaded.

**Comment by tfonteyn** [comment]
here you go: [6.1.1](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v6.1.1/NeverTooManyBooks-6.1.1.apk)
