### ISSUE TITLE
[Whishlist] Change Amazon URL to a local one

### ISSUE THREAD

**Issue by coastgnu** [tfonteyn/NeverTooManyBooks#67]
E.g.:

Adding a book via <+> - 'Search for Title' - name: 'Duval Noah Harari',  title: 'Sapiens' gives a, let me call it, suboptimal answer.

Choosing <overflow menu> 'Amazon Menu…' goes to amazon.go.uk. The result also is suboptimal.
See:
https://www.amazon.co.uk/s?i=stripbooks&rh=p_27%3AYuval+Noah+Harari

See also [1] 

Changing the URL to amazon.de the answer is optimal.
All three books show up!
https://www.amazon.de/s?k=yuval+noah+harari+%2Csapiens%3A&crid=1BK94YOW3K59F&sprefix=yuval+noah+harari+sapiens+%2Caps%2C222&ref=nb_sb_noss_2

By changing the amazon URL from co.uk to de aside the name also the title appears in the search string!

So it would be great to configure an  additional or at least different Amazon URL.
An option to search for name and title by hand (co.uk) seems to be no solution, see [1]

@Mention: A search at thalia.de for name and title brings an optimal result. Another argument to enable a search via thalia.de . See  [Feature request] Add thalia.de as websource #62 

[1] changing the search string as in the DE URL to
https://www.amazon.co.uk/s?k=yuval+noah+harari%2C+sapiens%3A&crid=2NTUE0LSGYL4Q&sprefix=yuval+noah+harari+sapiens+%2Caps%2C154&ref=nb_sb_noss_2
shows the same result

**Comment by tfonteyn** [comment]
Please check the [docs](https://github.com/tfonteyn/NeverTooManyBooks/wiki)

First time users, second paragraph.

**Comment by coastgnu** [comment]
Pardon for the noise

RTFM, I always tell my trainees …

Me, covers under a stone 
Don't know the dutch saying, but it's the same in our Frisian, DE_nds
(german: sich unter einem Stein verstecken. Insekten verstecken sich unter Steinen .)

**Comment by tfonteyn** [comment]
hehe - I've done this myself all to often.

RTFM:  Read the FINE manual  ;-)

(if the developer at least wrote one.... oopsie... work-in-progress as they say)
