### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Wurftaube** [tfonteyn/NeverTooManyBooks#69]
When trying to change the year of publication the app crashs.

[ntmb-crash-2024-06-18T19_27_41.451096.txt](https://github.com/user-attachments/files/15890416/ntmb-crash-2024-06-18T19_27_41.451096.txt)

**Comment by tfonteyn** [comment]
already fixed :)

Please install [6.1.2](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v6.1.2/NeverTooManyBooks-6.1.2.apk)

**Comment by tfonteyn** [comment]
In case you have not installed 6.1.2 yet,  there is now [6.1.3](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v6.1.3/NeverTooManyBooks-6.1.3.apk)  (unrelated fix to this issue)
