### ISSUE TITLE
Update fields - for all books

### ISSUE THREAD

**Issue by GaryOwhere** [tfonteyn/NeverTooManyBooks#7]
Is there a way to initiate a "Update fields" process for all books in a collection?  Or at least to Update fields for all books in a bookshelf or expanded section?  I realize that for a large book collection this may take some time, but it seems a laborious process to update books for each author individually.

**Comment by tfonteyn** [comment]
I actually had "for all books in a bookshelf" enabled in the past (the code still exists but is disabled) as I was never happy with it. You are right it can take an **very**  long time when there are a lot of books.
I partially implemented a 'stop/resume' but it was rather crude and precarious. I put the idea back on the 'todo' list.
I'll bump this up to revisit for a new release (after the 4.2 release which is going out any day soon now)

Currently 'update fields' is enabled for these nodes and all books under them (and single books obviously)
- authors
- series
- publishers
- date added
- date acquired,
- date published

As a work around you should be able to use a booklist style which sorts on for example "Date added" with a top-level group of "year added". You can then update all books you added that year in one go (but without stop/resume!)
There is a builtin-style "Date Added" which you can use (either directly, or duplicate/customize).
Let me know if you need more details on how to do this.

I suggest you are selective on which sites (search-sources) you want to enable for this update, as well as if to fetch cover pictures. For the latter I tend to use the "skip to next book without cover" as most books get a cover on the initial entry anyhow.

**Comment by GaryOwhere** [comment]
@tfonteyn ... Thanks for the info and tips.  I did clone the "Date Added" booklist style, and used the Year Added group to Update books for each year.  That did the trick!  I have 849 books in my collection, and they are all now updated. 

I previously used the Book Catalogue app, and successfully imported the backup file from that app into NeverTooManyBooks.  That import worked well.  Thanks for forking that app, and looking forward to your enhancements.  Truly, there are NeverTooManyBooks!

**Comment by tfonteyn** [comment]
my pleasure - feel free to open new issues when you need help
