### ISSUE TITLE
[Feature request] Make bol.com toplevel domain editable

### ISSUE THREAD

**Issue by coastgnu** [tfonteyn/NeverTooManyBooks#73]
Searching bol.de for German books gives a better result than for bol.com

So making the bol toplevel domain editable as it is for amazon would be helpful.

regards
thomas

**Comment by tfonteyn** [comment]
ah ? I didn't realise they had a German site.

okido, I'll add that functionality - easy enough; will be in 6.2

**Comment by tfonteyn** [comment]
ouch.... some bad news I'm afraid.  The site bol.de is a different company.

Bol.de is in fact just a brand of Thalia.de and has nothing to do with bol.com.
Try it out, look up the same isbn on both thalia.de and bol.de. The book page is near identical.

So it's not a matter of changing the url, it would need an entire new search-engine implementation... and then we're back to #62 of course.

Is your experience with amazon.de not as good as I hoped?

**Comment by coastgnu** [comment]
yes and NO

yes, better than amazon.com

NO, because it's amazon …

I try to avoid the amazonisation of our local merchants wherever I can

Especially when it comes to books

**Comment by tfonteyn** [comment]
hehe - I agree totally with your statements :)

But keep in mind this app is a collecting-tool. The lookups are for collecting data about the book, they are not to take you to a shopping site. (Granted, there is the amazon/bol.com searches for 'books from/in').

I'll close this issue, as there is little point in supporting bol.de. But I'll reopen the question on thalia.de, and while I cannot make any promises, I'll try to revisit it in the future.
