### ISSUE TITLE
Reproducible Builds (for IzzyOnDroid)

### ISSUE THREAD

**Issue by obfusk** [tfonteyn/NeverTooManyBooks#75]
At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients?lang=en)).

Your app [has been reproducible](https://apt.izzysoft.de/fdroid/index/apk/com.hardbacknutter.nevertoomanybooks) for quite a while (see the green shields) :tada:. Unfortunately, it has [embedded timestamps](https://reproducible-builds.org/docs/timestamps/), the biggest source of reproducibility issues. We can work around those, but it requires manual work to keep up to date. It would be a lot easier for us if you could make the build fully deterministic.

I see the embedded timestamp is used in the about screen. Is that really needed? If so, how about using e.g. the output of `git log -1 --pretty=%ct` instead of the current time? That would be deterministic.

https://github.com/tfonteyn/NeverTooManyBooks/blob/4ce3ba4e306fece4f611d05bb5bda1a31d073eea/app/build.gradle#L133-L135

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on Reproducible Builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds).

Thank you!

cc @IzzySoft

**Comment by tfonteyn** [comment]
I suppose it matters little...  it was done to differentiate between 'my' builds and potentially others. But the signing should be sufficient.

I've removed it [c958730](https://github.com/tfonteyn/NeverTooManyBooks/commit/c9587306c8ed604c4535b28a2b70b464a3e1eff0).

Next version won't contain it.

**Comment by obfusk** [comment]
Thanks!
