### ISSUE TITLE
all books vs my books

### ISSUE THREAD

**Issue by didispe** [tfonteyn/NeverTooManyBooks#78]
the number of books displayed in "my books" is lesser than in "all books"
but all books are my books. So how can I adjust the numbers or add the missing books to my books

**Comment by tfonteyn** [comment]
This is typically down to the style (see [docs)](https://github.com/tfonteyn/NeverTooManyBooks/wiki#styles) applied on the bookshelf. 

You can for example have books with multiple authors show up "under each author". 

The "My Books" bookshelf is just the default, create others as needed (main menu panel, "Bookshelves")
The "All books" bookshelf is a bit special as it's a virtual shelf . Basically it ignores the actual bookshelf a book is on to create/show the list.

You can see the absolute/exact amount of book in the "About" screen.

If in doubt, feel free to extract "styles.json" from a backup zip and upload it. I'm happy to take a look in detail.

**Comment by tfonteyn** [comment]
any feedback or do you have more questions on this?

**Comment by didispe** [comment]
Thanks, everything works well, great app!
