### ISSUE TITLE
Build fails for v6.3.1

### ISSUE THREAD

**Issue by IzzySoft** [tfonteyn/NeverTooManyBooks#79]
The build for v6.3.1 fails:

```
> Task :app:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

> Task :app:compileReleaseJavaWithJavac FAILED
> Task :core:lintVitalAnalyzeRelease

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
194 actionable tasks: 194 executed
Configuration cache entry stored.
> Compilation failed; see the compiler error output for details.
```

Trying to find out how you were able to build, I've looked into the versionInfo contained in your APK – which says it was built from commit 10238365d3130b027ab73ea4a69cc1907807069c – the commit your tag points to (7e6b3d9d150c2711c426b2e4293b8e83f571a84d) is not even part of this repository. Most likely you first built, then squashed, then tagged – which is a guarantee for RB to fail. Our framework recognized that and tried to `git reset --soft` to the embedded hash, but that felt too (see above). Directly checking out the commit (instead of performing a soft-reset) helped to a successful build, which then only had a small difference:

```diff
  -rw-r--r--  0.0 unx      120 b-      117 defN 1981-01-01 01:01:02 a1ea1900 META-INF/version-control-info.textproto
- -rw-r--r--  0.0 unx     2344 b-     2344 stor 1981-01-01 01:01:02 0af14638 assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx     2353 b-     2353 stor 1981-01-01 01:01:02 72dc4a8a assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx      318 b-      318 stor 1981-01-01 01:01:02 8a59412e assets/dexopt/baseline.profm
```

Looking at the baseline diff, this seems to be a non-deterministic build (what we call "flaky"):

```diff
 dex_data 0
-  num_hot_method_ids=924
+  num_hot_method_ids=923
   num_type_ids=317
```

which we luckily can also compensate (and succeeded with here).

It would be good if you could make sure the tag always points to the commit your APK was built from (what we call the "first basic rule" in our [hints on Reproducible Builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds)) – isn't that what you released then (the commit the APK was built from)? It would save us all a lot of work and headache :wink: (yeah, took me about an hour to figure out what's wrong with your app and fix it – half of that for the "wrong commit"; the "flaky" part is of course not your fault).

Thanks in advance for taking care :wink:

**Comment by tfonteyn** [comment]
now that sound very weird.

> took me about an hour to figure out

You shouldn't have 😨  you should have just bumped it directly back to me.

Too late for today, but I'll check this out tomorrow and "do the needful" (ahum)

I'll keep you posted.

**Comment by IzzySoft** [comment]
> You shouldn't have 😨 you should have just bumped it directly back to me.

Eh. At IzzyOnDroid we try to support "our" devs as good as we can. So in this case, I hope the analysis helps you tackling the issue :wink:

> Too late for today, but I'll check this out tomorrow and "do the needful" (ahum)

Yeah, for **the current release** (v6.3.1) it's too late now. Luckily I managed to get it RB, and no modifications to **your** APK were needed. I guess just following the "golden rule" should be all that's needed from your side: flaky builds are an issue of the toolkit you hardly can do anything about (I've established the "flake-shake" here for NeverTooManyBooks which luckily managed to take care for that (building in a loop until either the checksum of the baseline matches or the build times out).

> I'll keep you posted.

Thanks! If you have questions, just raise them, I'll try to answer them wherever I can.

**Comment by tfonteyn** [comment]
> At IzzyOnDroid we try to support "our" devs as good as we can.

You're too kind 🥇

I've no idea what exactly went wrong, but one thing is certain... I must have goofed up somehow.

> Yeah, for the current release (v6.3.1) it's too late now.

ok. I'll add a quick note to the github release notes about building 6.3.1 being bleeped; and I won't spend any time on trying to fix it. The 6.3.x branch should be a dead-end anyhow.

Version 6.3.1 was a backport from dev for #77. Next up will a regular release 6.4.0.

**Comment by IzzySoft** [comment]
> I must have goofed up somehow.

Don't we all from time to time? Trick is to make it as rare as possible :stuck_out_tongue_winking_eye:

> ok. I'll add a quick note to the github release notes about building 6.3.1 being bleeped; and I won't spend any time on trying to fix it.

For the note: "check out from 10238365d3130b027ab73ea4a69cc1907807069c instead" (that's what you've built the APK from, see above, and what works – "flaky" just applies to RB).

Looking forward to 6.4.x then!
