### ISSUE TITLE
Visual Button-Bug in DE

### ISSUE THREAD

**Issue by Zoriot** [tfonteyn/NeverTooManyBooks#8]
Hey,
in my default Language Deutsch/German the Buttons for the Bookfilter on the bottom are glitched into each other. 

Android: 13 
Display Size: 6,55 Inch
Version: 4.3.0

If you need any more Information feel free to ask.
Thanks for this amazing app, I really like it.

![Screenshot_2023-05-11-21-01-55-49_77ccd5256e3281f8dad3196e1e334f71](https://github.com/tfonteyn/NeverTooManyBooks/assets/59896907/cdbc94c1-ac59-4d98-932f-f9f6fd46086d)

**Comment by tfonteyn** [comment]
thanks for this report.

I've just pushed 4.3.1 out, but that will not have a fix for this issue yet. I have however already verified and will be fixing it soon.

Long story short: the underlying filter-dialog/list is supposed to be full-screen and hence (in test) had enough space for the button text. I'll likely fix this in the next couple of days and push a new release - I'll let you know.

Thanks for the kind words :)

**Comment by tfonteyn** [comment]
I've pushed [4.3.2](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.3.2) which fixes this issue.

Should you have any (other) issues, please report them here :)
