### ISSUE TITLE
Book progress

### ISSUE THREAD

**Issue by Simx72** [tfonteyn/NeverTooManyBooks#80]
It would be nice if you could add the current page of a book and the total pages and then see a progress bar showing how much "percentage" you have read.

**Comment by tfonteyn** [comment]
Unless I misunderstand your request, you can already do this.

You can choose to track progress either as simple "Read/Unread" status (default), by either a percentage (0..100%), or by page number.

Use "Settings", the section "Style": Edit default settings. Then scroll down to "Track your progress".
This will set your choice for all built-in styles.

When you clone a built-in style for customization, edit your custom style; same setting.
Keep in mind defaults are copied at the time of creating a custom style; settings are not hierarchical.

See [styles](https://github.com/tfonteyn/NeverTooManyBooks/wiki#styles).
Docs are written as questions come in ...  I'll add the above to the docs tomorrow.

**Comment by tfonteyn** [comment]
The [style docs](https://github.com/tfonteyn/NeverTooManyBooks/wiki#styles) have now been updated with more details.

Of course, let me know if you have more questions

**Comment by Simx72** [comment]
Thank you so much

I didn't know, the option is a little hidden though 😅

**Comment by tfonteyn** [comment]
> the option is a little hidden though

true - I should take some time to do a better job on the docs... but I always seem to have another book to read first 😊
