### ISSUE TITLE
Keeps crashing when creating an author

### ISSUE THREAD

**Issue by maverick74** [tfonteyn/NeverTooManyBooks#9]
New bug:
Keeps crashing everytime I try to create an Author!!!

I insert the ISBN, it does not get neither the title nor the author name and when try to create the author it crashes!

I also tried adding manually and got the same result!

(Also, shouldn't the language offer a pre-set languages list?)

**Comment by tfonteyn** [comment]
I really should have tested/waited a bit before the new release so short after coming back from holiday... 

    Author

I'll check and fix asap.

    language

It probably should. As it is now, the drop-down simply shows what is already stored in the database. Initially this is of course empty. Maybe I need to add some predefined ones just like I do with the currency dropdown.

**Comment by tfonteyn** [comment]
google bug:  [https://issuetracker.google.com/issues/181655428](https://issuetracker.google.com/issues/181655428)
"Alpha" workaround works in api<29 but fails with non-latin charsets.

**Comment by tfonteyn** [comment]
and it's fixed in [v4.3.3](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.3.3)

Once again, thanks for your patience :)
